/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.x402api.client.model.PaymentReadinessBlocker;
import com.x402api.client.model.PaymentReadinessRailStatusEnum;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.x402api.client.core.JSON;

/**
 * CanonicalPaymentReadinessRail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CanonicalPaymentReadinessRail {
  public static final String SERIALIZED_NAME_ASSET_ID = "asset_id";
  @SerializedName(SERIALIZED_NAME_ASSET_ID)
  @javax.annotation.Nonnull
  private String assetId;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  @javax.annotation.Nonnull
  private String network;

  public static final String SERIALIZED_NAME_SYMBOL = "symbol";
  @SerializedName(SERIALIZED_NAME_SYMBOL)
  @javax.annotation.Nonnull
  private String symbol;

  public static final String SERIALIZED_NAME_SELECTED = "selected";
  @SerializedName(SERIALIZED_NAME_SELECTED)
  @javax.annotation.Nonnull
  private Boolean selected;

  public static final String SERIALIZED_NAME_WALLET_READY = "wallet_ready";
  @SerializedName(SERIALIZED_NAME_WALLET_READY)
  @javax.annotation.Nonnull
  private Boolean walletReady;

  public static final String SERIALIZED_NAME_PLATFORM_AVAILABLE = "platform_available";
  @SerializedName(SERIALIZED_NAME_PLATFORM_AVAILABLE)
  @javax.annotation.Nonnull
  private Boolean platformAvailable;

  public static final String SERIALIZED_NAME_ACCEPTING_NEW_PAYMENTS = "accepting_new_payments";
  @SerializedName(SERIALIZED_NAME_ACCEPTING_NEW_PAYMENTS)
  @javax.annotation.Nonnull
  private Boolean acceptingNewPayments;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private PaymentReadinessRailStatusEnum status;

  public static final String SERIALIZED_NAME_BLOCKERS = "blockers";
  @SerializedName(SERIALIZED_NAME_BLOCKERS)
  @javax.annotation.Nonnull
  private List<PaymentReadinessBlocker> blockers = new ArrayList<>();

  public CanonicalPaymentReadinessRail() {
  }

  public CanonicalPaymentReadinessRail(
     String assetId,
     String network,
     String symbol,
     Boolean selected,
     Boolean walletReady,
     Boolean platformAvailable,
     Boolean acceptingNewPayments,
     PaymentReadinessRailStatusEnum status,
     List<PaymentReadinessBlocker> blockers
  ) {
    this();
    this.assetId = assetId;
    this.network = network;
    this.symbol = symbol;
    this.selected = selected;
    this.walletReady = walletReady;
    this.platformAvailable = platformAvailable;
    this.acceptingNewPayments = acceptingNewPayments;
    this.status = status;
    this.blockers = blockers;
  }

  /**
   * Get assetId
   * @return assetId
   */
  @javax.annotation.Nonnull
  public String getAssetId() {
    return assetId;
  }



  /**
   * Get network
   * @return network
   */
  @javax.annotation.Nonnull
  public String getNetwork() {
    return network;
  }



  /**
   * Get symbol
   * @return symbol
   */
  @javax.annotation.Nonnull
  public String getSymbol() {
    return symbol;
  }



  /**
   * Get selected
   * @return selected
   */
  @javax.annotation.Nonnull
  public Boolean getSelected() {
    return selected;
  }



  /**
   * Get walletReady
   * @return walletReady
   */
  @javax.annotation.Nonnull
  public Boolean getWalletReady() {
    return walletReady;
  }



  /**
   * Get platformAvailable
   * @return platformAvailable
   */
  @javax.annotation.Nonnull
  public Boolean getPlatformAvailable() {
    return platformAvailable;
  }



  /**
   * Get acceptingNewPayments
   * @return acceptingNewPayments
   */
  @javax.annotation.Nonnull
  public Boolean getAcceptingNewPayments() {
    return acceptingNewPayments;
  }



  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public PaymentReadinessRailStatusEnum getStatus() {
    return status;
  }



  /**
   * Get blockers
   * @return blockers
   */
  @javax.annotation.Nonnull
  public List<PaymentReadinessBlocker> getBlockers() {
    return blockers;
  }


  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CanonicalPaymentReadinessRail instance itself
   */
  public CanonicalPaymentReadinessRail putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CanonicalPaymentReadinessRail canonicalPaymentReadinessRail = (CanonicalPaymentReadinessRail) o;
    return Objects.equals(this.assetId, canonicalPaymentReadinessRail.assetId) &&
        Objects.equals(this.network, canonicalPaymentReadinessRail.network) &&
        Objects.equals(this.symbol, canonicalPaymentReadinessRail.symbol) &&
        Objects.equals(this.selected, canonicalPaymentReadinessRail.selected) &&
        Objects.equals(this.walletReady, canonicalPaymentReadinessRail.walletReady) &&
        Objects.equals(this.platformAvailable, canonicalPaymentReadinessRail.platformAvailable) &&
        Objects.equals(this.acceptingNewPayments, canonicalPaymentReadinessRail.acceptingNewPayments) &&
        Objects.equals(this.status, canonicalPaymentReadinessRail.status) &&
        Objects.equals(this.blockers, canonicalPaymentReadinessRail.blockers)&&
        Objects.equals(this.additionalProperties, canonicalPaymentReadinessRail.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetId, network, symbol, selected, walletReady, platformAvailable, acceptingNewPayments, status, blockers, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CanonicalPaymentReadinessRail {\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    selected: ").append(toIndentedString(selected)).append("\n");
    sb.append("    walletReady: ").append(toIndentedString(walletReady)).append("\n");
    sb.append("    platformAvailable: ").append(toIndentedString(platformAvailable)).append("\n");
    sb.append("    acceptingNewPayments: ").append(toIndentedString(acceptingNewPayments)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    blockers: ").append(toIndentedString(blockers)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("asset_id", "network", "symbol", "selected", "wallet_ready", "platform_available", "accepting_new_payments", "status", "blockers"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("asset_id", "network", "symbol", "selected", "wallet_ready", "platform_available", "accepting_new_payments", "status", "blockers"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CanonicalPaymentReadinessRail
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CanonicalPaymentReadinessRail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CanonicalPaymentReadinessRail is not found in the empty JSON string", CanonicalPaymentReadinessRail.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CanonicalPaymentReadinessRail.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("asset_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `asset_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asset_id").toString()));
      }
      if (!jsonObj.get("network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network").toString()));
      }
      if (!jsonObj.get("symbol").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbol").toString()));
      }
      // validate the required field `status`
      PaymentReadinessRailStatusEnum.validateJsonElement(jsonObj.get("status"));
      if (jsonObj.get("blockers") != null) {
        if (!jsonObj.get("blockers").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `blockers` to be an array in the JSON string but got `%s`", jsonObj.get("blockers").toString()));
        }
        JsonArray jsonArrayblockers = jsonObj.getAsJsonArray("blockers");
        // validate the required field `blockers` (array)
        for (int i = 0; i < jsonArrayblockers.size(); i++) {
          PaymentReadinessBlocker.validateJsonElement(jsonArrayblockers.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CanonicalPaymentReadinessRail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CanonicalPaymentReadinessRail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CanonicalPaymentReadinessRail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CanonicalPaymentReadinessRail.class));

       return (TypeAdapter<T>) new TypeAdapter<CanonicalPaymentReadinessRail>() {
           @Override
           public void write(JsonWriter out, CanonicalPaymentReadinessRail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CanonicalPaymentReadinessRail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             CanonicalPaymentReadinessRail instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CanonicalPaymentReadinessRail given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CanonicalPaymentReadinessRail
   * @throws IOException if the JSON string is invalid with respect to CanonicalPaymentReadinessRail
   */
  public static CanonicalPaymentReadinessRail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CanonicalPaymentReadinessRail.class);
  }

  /**
   * Convert an instance of CanonicalPaymentReadinessRail to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
