/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.x402api.client.model.DynamicChargePrice;
import com.x402api.client.model.FeePolicyDocument;
import com.x402api.client.model.NetworkFeeAlternative;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.x402api.client.core.JSON;

/**
 * DynamicChargeResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class DynamicChargeResponse {
  public static final String SERIALIZED_NAME_CHARGE_ID = "charge_id";
  @SerializedName(SERIALIZED_NAME_CHARGE_ID)
  @javax.annotation.Nonnull
  private UUID chargeId;

  public static final String SERIALIZED_NAME_CHARGE_DIGEST = "charge_digest";
  @SerializedName(SERIALIZED_NAME_CHARGE_DIGEST)
  @javax.annotation.Nonnull
  private String chargeDigest;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  @javax.annotation.Nonnull
  private UUID orderId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private String status;

  public static final String SERIALIZED_NAME_RESOURCE_VERSION_ID = "resource_version_id";
  @SerializedName(SERIALIZED_NAME_RESOURCE_VERSION_ID)
  @javax.annotation.Nonnull
  private UUID resourceVersionId;

  public static final String SERIALIZED_NAME_PAYMENT_IDENTIFIER = "payment_identifier";
  @SerializedName(SERIALIZED_NAME_PAYMENT_IDENTIFIER)
  @javax.annotation.Nonnull
  private String paymentIdentifier;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime expiresAt;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_PRICES = "prices";
  @SerializedName(SERIALIZED_NAME_PRICES)
  @javax.annotation.Nonnull
  private List<DynamicChargePrice> prices = new ArrayList<>();

  public static final String SERIALIZED_NAME_REQUESTED_EXPIRES_IN_SECONDS = "requested_expires_in_seconds";
  @SerializedName(SERIALIZED_NAME_REQUESTED_EXPIRES_IN_SECONDS)
  @javax.annotation.Nonnull
  private Integer requestedExpiresInSeconds;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nonnull
  private Map<String, Object> metadata = new HashMap<>();

  public static final String SERIALIZED_NAME_METADATA_DIGEST = "metadata_digest";
  @SerializedName(SERIALIZED_NAME_METADATA_DIGEST)
  @javax.annotation.Nonnull
  private String metadataDigest;

  public static final String SERIALIZED_NAME_PAYMENT_REQUIRED = "payment_required";
  @SerializedName(SERIALIZED_NAME_PAYMENT_REQUIRED)
  @javax.annotation.Nullable
  private Object paymentRequired = null;

  public static final String SERIALIZED_NAME_PAYMENT_REQUIRED_HEADER = "payment_required_header";
  @SerializedName(SERIALIZED_NAME_PAYMENT_REQUIRED_HEADER)
  @javax.annotation.Nonnull
  private String paymentRequiredHeader;

  public static final String SERIALIZED_NAME_ELIGIBLE_ALTERNATIVES = "eligible_alternatives";
  @SerializedName(SERIALIZED_NAME_ELIGIBLE_ALTERNATIVES)
  @javax.annotation.Nonnull
  private List<NetworkFeeAlternative> eligibleAlternatives = new ArrayList<>();

  public static final String SERIALIZED_NAME_FEE_POLICY = "fee_policy";
  @SerializedName(SERIALIZED_NAME_FEE_POLICY)
  @javax.annotation.Nonnull
  private FeePolicyDocument feePolicy;

  public static final String SERIALIZED_NAME_FEE_QUOTE_DIGEST = "fee_quote_digest";
  @SerializedName(SERIALIZED_NAME_FEE_QUOTE_DIGEST)
  @javax.annotation.Nonnull
  private String feeQuoteDigest;

  public DynamicChargeResponse() {
  }

  public DynamicChargeResponse chargeId(@javax.annotation.Nonnull UUID chargeId) {
    this.chargeId = chargeId;
    return this;
  }

  /**
   * Get chargeId
   * @return chargeId
   */
  @javax.annotation.Nonnull
  public UUID getChargeId() {
    return chargeId;
  }

  public void setChargeId(@javax.annotation.Nonnull UUID chargeId) {
    this.chargeId = chargeId;
  }


  public DynamicChargeResponse chargeDigest(@javax.annotation.Nonnull String chargeDigest) {
    this.chargeDigest = chargeDigest;
    return this;
  }

  /**
   * Get chargeDigest
   * @return chargeDigest
   */
  @javax.annotation.Nonnull
  public String getChargeDigest() {
    return chargeDigest;
  }

  public void setChargeDigest(@javax.annotation.Nonnull String chargeDigest) {
    this.chargeDigest = chargeDigest;
  }


  public DynamicChargeResponse orderId(@javax.annotation.Nonnull UUID orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Get orderId
   * @return orderId
   */
  @javax.annotation.Nonnull
  public UUID getOrderId() {
    return orderId;
  }

  public void setOrderId(@javax.annotation.Nonnull UUID orderId) {
    this.orderId = orderId;
  }


  public DynamicChargeResponse status(@javax.annotation.Nonnull String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull String status) {
    this.status = status;
  }


  public DynamicChargeResponse resourceVersionId(@javax.annotation.Nonnull UUID resourceVersionId) {
    this.resourceVersionId = resourceVersionId;
    return this;
  }

  /**
   * Get resourceVersionId
   * @return resourceVersionId
   */
  @javax.annotation.Nonnull
  public UUID getResourceVersionId() {
    return resourceVersionId;
  }

  public void setResourceVersionId(@javax.annotation.Nonnull UUID resourceVersionId) {
    this.resourceVersionId = resourceVersionId;
  }


  public DynamicChargeResponse paymentIdentifier(@javax.annotation.Nonnull String paymentIdentifier) {
    this.paymentIdentifier = paymentIdentifier;
    return this;
  }

  /**
   * Get paymentIdentifier
   * @return paymentIdentifier
   */
  @javax.annotation.Nonnull
  public String getPaymentIdentifier() {
    return paymentIdentifier;
  }

  public void setPaymentIdentifier(@javax.annotation.Nonnull String paymentIdentifier) {
    this.paymentIdentifier = paymentIdentifier;
  }


  public DynamicChargeResponse expiresAt(@javax.annotation.Nonnull OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nonnull OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public DynamicChargeResponse createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public DynamicChargeResponse prices(@javax.annotation.Nonnull List<DynamicChargePrice> prices) {
    this.prices = prices;
    return this;
  }

  public DynamicChargeResponse addPricesItem(DynamicChargePrice pricesItem) {
    if (this.prices == null) {
      this.prices = new ArrayList<>();
    }
    this.prices.add(pricesItem);
    return this;
  }

  /**
   * Get prices
   * @return prices
   */
  @javax.annotation.Nonnull
  public List<DynamicChargePrice> getPrices() {
    return prices;
  }

  public void setPrices(@javax.annotation.Nonnull List<DynamicChargePrice> prices) {
    this.prices = prices;
  }


  public DynamicChargeResponse requestedExpiresInSeconds(@javax.annotation.Nonnull Integer requestedExpiresInSeconds) {
    this.requestedExpiresInSeconds = requestedExpiresInSeconds;
    return this;
  }

  /**
   * Get requestedExpiresInSeconds
   * @return requestedExpiresInSeconds
   */
  @javax.annotation.Nonnull
  public Integer getRequestedExpiresInSeconds() {
    return requestedExpiresInSeconds;
  }

  public void setRequestedExpiresInSeconds(@javax.annotation.Nonnull Integer requestedExpiresInSeconds) {
    this.requestedExpiresInSeconds = requestedExpiresInSeconds;
  }


  public DynamicChargeResponse metadata(@javax.annotation.Nonnull Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public DynamicChargeResponse putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Tenant application metadata frozen into the charge digest. Maximum canonical size is 16 KiB; floating-point numbers are not accepted.
   * @return metadata
   */
  @javax.annotation.Nonnull
  public Map<String, Object> getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nonnull Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public DynamicChargeResponse metadataDigest(@javax.annotation.Nonnull String metadataDigest) {
    this.metadataDigest = metadataDigest;
    return this;
  }

  /**
   * Get metadataDigest
   * @return metadataDigest
   */
  @javax.annotation.Nonnull
  public String getMetadataDigest() {
    return metadataDigest;
  }

  public void setMetadataDigest(@javax.annotation.Nonnull String metadataDigest) {
    this.metadataDigest = metadataDigest;
  }


  public DynamicChargeResponse paymentRequired(@javax.annotation.Nullable Object paymentRequired) {
    this.paymentRequired = paymentRequired;
    return this;
  }

  /**
   * Get paymentRequired
   * @return paymentRequired
   */
  @javax.annotation.Nullable
  public Object getPaymentRequired() {
    return paymentRequired;
  }

  public void setPaymentRequired(@javax.annotation.Nullable Object paymentRequired) {
    this.paymentRequired = paymentRequired;
  }


  public DynamicChargeResponse paymentRequiredHeader(@javax.annotation.Nonnull String paymentRequiredHeader) {
    this.paymentRequiredHeader = paymentRequiredHeader;
    return this;
  }

  /**
   * Get paymentRequiredHeader
   * @return paymentRequiredHeader
   */
  @javax.annotation.Nonnull
  public String getPaymentRequiredHeader() {
    return paymentRequiredHeader;
  }

  public void setPaymentRequiredHeader(@javax.annotation.Nonnull String paymentRequiredHeader) {
    this.paymentRequiredHeader = paymentRequiredHeader;
  }


  public DynamicChargeResponse eligibleAlternatives(@javax.annotation.Nonnull List<NetworkFeeAlternative> eligibleAlternatives) {
    this.eligibleAlternatives = eligibleAlternatives;
    return this;
  }

  public DynamicChargeResponse addEligibleAlternativesItem(NetworkFeeAlternative eligibleAlternativesItem) {
    if (this.eligibleAlternatives == null) {
      this.eligibleAlternatives = new ArrayList<>();
    }
    this.eligibleAlternatives.add(eligibleAlternativesItem);
    return this;
  }

  /**
   * Get eligibleAlternatives
   * @return eligibleAlternatives
   */
  @javax.annotation.Nonnull
  public List<NetworkFeeAlternative> getEligibleAlternatives() {
    return eligibleAlternatives;
  }

  public void setEligibleAlternatives(@javax.annotation.Nonnull List<NetworkFeeAlternative> eligibleAlternatives) {
    this.eligibleAlternatives = eligibleAlternatives;
  }


  public DynamicChargeResponse feePolicy(@javax.annotation.Nonnull FeePolicyDocument feePolicy) {
    this.feePolicy = feePolicy;
    return this;
  }

  /**
   * Get feePolicy
   * @return feePolicy
   */
  @javax.annotation.Nonnull
  public FeePolicyDocument getFeePolicy() {
    return feePolicy;
  }

  public void setFeePolicy(@javax.annotation.Nonnull FeePolicyDocument feePolicy) {
    this.feePolicy = feePolicy;
  }


  public DynamicChargeResponse feeQuoteDigest(@javax.annotation.Nonnull String feeQuoteDigest) {
    this.feeQuoteDigest = feeQuoteDigest;
    return this;
  }

  /**
   * Get feeQuoteDigest
   * @return feeQuoteDigest
   */
  @javax.annotation.Nonnull
  public String getFeeQuoteDigest() {
    return feeQuoteDigest;
  }

  public void setFeeQuoteDigest(@javax.annotation.Nonnull String feeQuoteDigest) {
    this.feeQuoteDigest = feeQuoteDigest;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DynamicChargeResponse instance itself
   */
  public DynamicChargeResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DynamicChargeResponse dynamicChargeResponse = (DynamicChargeResponse) o;
    return Objects.equals(this.chargeId, dynamicChargeResponse.chargeId) &&
        Objects.equals(this.chargeDigest, dynamicChargeResponse.chargeDigest) &&
        Objects.equals(this.orderId, dynamicChargeResponse.orderId) &&
        Objects.equals(this.status, dynamicChargeResponse.status) &&
        Objects.equals(this.resourceVersionId, dynamicChargeResponse.resourceVersionId) &&
        Objects.equals(this.paymentIdentifier, dynamicChargeResponse.paymentIdentifier) &&
        Objects.equals(this.expiresAt, dynamicChargeResponse.expiresAt) &&
        Objects.equals(this.createdAt, dynamicChargeResponse.createdAt) &&
        Objects.equals(this.prices, dynamicChargeResponse.prices) &&
        Objects.equals(this.requestedExpiresInSeconds, dynamicChargeResponse.requestedExpiresInSeconds) &&
        Objects.equals(this.metadata, dynamicChargeResponse.metadata) &&
        Objects.equals(this.metadataDigest, dynamicChargeResponse.metadataDigest) &&
        Objects.equals(this.paymentRequired, dynamicChargeResponse.paymentRequired) &&
        Objects.equals(this.paymentRequiredHeader, dynamicChargeResponse.paymentRequiredHeader) &&
        Objects.equals(this.eligibleAlternatives, dynamicChargeResponse.eligibleAlternatives) &&
        Objects.equals(this.feePolicy, dynamicChargeResponse.feePolicy) &&
        Objects.equals(this.feeQuoteDigest, dynamicChargeResponse.feeQuoteDigest)&&
        Objects.equals(this.additionalProperties, dynamicChargeResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chargeId, chargeDigest, orderId, status, resourceVersionId, paymentIdentifier, expiresAt, createdAt, prices, requestedExpiresInSeconds, metadata, metadataDigest, paymentRequired, paymentRequiredHeader, eligibleAlternatives, feePolicy, feeQuoteDigest, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DynamicChargeResponse {\n");
    sb.append("    chargeId: ").append(toIndentedString(chargeId)).append("\n");
    sb.append("    chargeDigest: ").append(toIndentedString(chargeDigest)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    resourceVersionId: ").append(toIndentedString(resourceVersionId)).append("\n");
    sb.append("    paymentIdentifier: ").append(toIndentedString(paymentIdentifier)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    prices: ").append(toIndentedString(prices)).append("\n");
    sb.append("    requestedExpiresInSeconds: ").append(toIndentedString(requestedExpiresInSeconds)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    metadataDigest: ").append(toIndentedString(metadataDigest)).append("\n");
    sb.append("    paymentRequired: ").append(toIndentedString(paymentRequired)).append("\n");
    sb.append("    paymentRequiredHeader: ").append(toIndentedString(paymentRequiredHeader)).append("\n");
    sb.append("    eligibleAlternatives: ").append(toIndentedString(eligibleAlternatives)).append("\n");
    sb.append("    feePolicy: ").append(toIndentedString(feePolicy)).append("\n");
    sb.append("    feeQuoteDigest: ").append(toIndentedString(feeQuoteDigest)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("charge_id", "charge_digest", "order_id", "status", "resource_version_id", "payment_identifier", "expires_at", "created_at", "prices", "requested_expires_in_seconds", "metadata", "metadata_digest", "payment_required", "payment_required_header", "eligible_alternatives", "fee_policy", "fee_quote_digest"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("charge_id", "charge_digest", "order_id", "status", "resource_version_id", "payment_identifier", "expires_at", "created_at", "prices", "requested_expires_in_seconds", "metadata", "metadata_digest", "payment_required", "payment_required_header", "eligible_alternatives", "fee_policy", "fee_quote_digest"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DynamicChargeResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DynamicChargeResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DynamicChargeResponse is not found in the empty JSON string", DynamicChargeResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DynamicChargeResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("charge_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `charge_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("charge_id").toString()));
      }
      if (!jsonObj.get("charge_digest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `charge_digest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("charge_digest").toString()));
      }
      if (!jsonObj.get("order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_id").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (!jsonObj.get("resource_version_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `resource_version_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resource_version_id").toString()));
      }
      if (!jsonObj.get("payment_identifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payment_identifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payment_identifier").toString()));
      }
      if (jsonObj.get("prices") != null) {
        if (!jsonObj.get("prices").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `prices` to be an array in the JSON string but got `%s`", jsonObj.get("prices").toString()));
        }
        JsonArray jsonArrayprices = jsonObj.getAsJsonArray("prices");
        // validate the required field `prices` (array)
        for (int i = 0; i < jsonArrayprices.size(); i++) {
          DynamicChargePrice.validateJsonElement(jsonArrayprices.get(i));
        }
      }
      if (!jsonObj.get("metadata_digest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `metadata_digest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("metadata_digest").toString()));
      }
      if (!jsonObj.get("payment_required_header").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payment_required_header` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payment_required_header").toString()));
      }
      if (jsonObj.get("eligible_alternatives") != null) {
        if (!jsonObj.get("eligible_alternatives").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `eligible_alternatives` to be an array in the JSON string but got `%s`", jsonObj.get("eligible_alternatives").toString()));
        }
        JsonArray jsonArrayeligibleAlternatives = jsonObj.getAsJsonArray("eligible_alternatives");
        // validate the required field `eligible_alternatives` (array)
        for (int i = 0; i < jsonArrayeligibleAlternatives.size(); i++) {
          NetworkFeeAlternative.validateJsonElement(jsonArrayeligibleAlternatives.get(i));
        }
      }
      // validate the required field `fee_policy`
      FeePolicyDocument.validateJsonElement(jsonObj.get("fee_policy"));
      if (!jsonObj.get("fee_quote_digest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fee_quote_digest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fee_quote_digest").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DynamicChargeResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DynamicChargeResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DynamicChargeResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DynamicChargeResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<DynamicChargeResponse>() {
           @Override
           public void write(JsonWriter out, DynamicChargeResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DynamicChargeResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             DynamicChargeResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DynamicChargeResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DynamicChargeResponse
   * @throws IOException if the JSON string is invalid with respect to DynamicChargeResponse
   */
  public static DynamicChargeResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DynamicChargeResponse.class);
  }

  /**
   * Convert an instance of DynamicChargeResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
