/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * * &#x60;signed_message&#x60; - Signed message * &#x60;onchain_canary&#x60; - On-chain canary
 */
@JsonAdapter(ExternalAddressProofMethodEnum.Adapter.class)
public enum ExternalAddressProofMethodEnum {

  SIGNED_MESSAGE("signed_message"),

  ONCHAIN_CANARY("onchain_canary"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  ExternalAddressProofMethodEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ExternalAddressProofMethodEnum fromValue(String value) {
    for (ExternalAddressProofMethodEnum b : ExternalAddressProofMethodEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<ExternalAddressProofMethodEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final ExternalAddressProofMethodEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ExternalAddressProofMethodEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ExternalAddressProofMethodEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ExternalAddressProofMethodEnum.fromValue(value);
  }
}
