/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * * &#x60;buyer_pays&#x60; - buyer_pays * &#x60;tenant_absorbs_up_to_cap&#x60; - tenant_absorbs_up_to_cap
 */
@JsonAdapter(FeePolicyModeInputEnum.Adapter.class)
public enum FeePolicyModeInputEnum {

  BUYER_PAYS("buyer_pays"),

  TENANT_ABSORBS_UP_TO_CAP("tenant_absorbs_up_to_cap"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  FeePolicyModeInputEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FeePolicyModeInputEnum fromValue(String value) {
    for (FeePolicyModeInputEnum b : FeePolicyModeInputEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<FeePolicyModeInputEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final FeePolicyModeInputEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public FeePolicyModeInputEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return FeePolicyModeInputEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    FeePolicyModeInputEnum.fromValue(value);
  }
}
