/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.x402api.client.model.NativeFeeObservationEvidence;
import com.x402api.client.model.NativeUsdObservationEvidence;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.x402api.client.core.JSON;

/**
 * Published shape for available and explicitly unavailable fee evidence.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class NetworkFeeEvidence {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nonnull
  private Integer version;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  @javax.annotation.Nonnull
  private String network;

  public static final String SERIALIZED_NAME_ASSET_ID = "assetId";
  @SerializedName(SERIALIZED_NAME_ASSET_ID)
  @javax.annotation.Nonnull
  private String assetId;

  public static final String SERIALIZED_NAME_PAYLOAD_PROFILE = "payloadProfile";
  @SerializedName(SERIALIZED_NAME_PAYLOAD_PROFILE)
  @javax.annotation.Nonnull
  private String payloadProfile;

  public static final String SERIALIZED_NAME_NATIVE_SYMBOL = "nativeSymbol";
  @SerializedName(SERIALIZED_NAME_NATIVE_SYMBOL)
  @javax.annotation.Nullable
  private String nativeSymbol;

  public static final String SERIALIZED_NAME_NATIVE_DECIMALS = "nativeDecimals";
  @SerializedName(SERIALIZED_NAME_NATIVE_DECIMALS)
  @javax.annotation.Nullable
  private Integer nativeDecimals;

  public static final String SERIALIZED_NAME_NATIVE_FEE_OBSERVATIONS = "nativeFeeObservations";
  @SerializedName(SERIALIZED_NAME_NATIVE_FEE_OBSERVATIONS)
  @javax.annotation.Nullable
  private List<NativeFeeObservationEvidence> nativeFeeObservations = new ArrayList<>();

  public static final String SERIALIZED_NAME_NATIVE_USD_OBSERVATIONS = "nativeUsdObservations";
  @SerializedName(SERIALIZED_NAME_NATIVE_USD_OBSERVATIONS)
  @javax.annotation.Nullable
  private List<NativeUsdObservationEvidence> nativeUsdObservations = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expiresAt";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private OffsetDateTime expiresAt;

  public NetworkFeeEvidence() {
  }

  public NetworkFeeEvidence type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  public NetworkFeeEvidence version(@javax.annotation.Nonnull Integer version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * minimum: 1
   * @return version
   */
  @javax.annotation.Nonnull
  public Integer getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nonnull Integer version) {
    this.version = version;
  }


  public NetworkFeeEvidence network(@javax.annotation.Nonnull String network) {
    this.network = network;
    return this;
  }

  /**
   * Get network
   * @return network
   */
  @javax.annotation.Nonnull
  public String getNetwork() {
    return network;
  }

  public void setNetwork(@javax.annotation.Nonnull String network) {
    this.network = network;
  }


  public NetworkFeeEvidence assetId(@javax.annotation.Nonnull String assetId) {
    this.assetId = assetId;
    return this;
  }

  /**
   * Get assetId
   * @return assetId
   */
  @javax.annotation.Nonnull
  public String getAssetId() {
    return assetId;
  }

  public void setAssetId(@javax.annotation.Nonnull String assetId) {
    this.assetId = assetId;
  }


  public NetworkFeeEvidence payloadProfile(@javax.annotation.Nonnull String payloadProfile) {
    this.payloadProfile = payloadProfile;
    return this;
  }

  /**
   * Get payloadProfile
   * @return payloadProfile
   */
  @javax.annotation.Nonnull
  public String getPayloadProfile() {
    return payloadProfile;
  }

  public void setPayloadProfile(@javax.annotation.Nonnull String payloadProfile) {
    this.payloadProfile = payloadProfile;
  }


  public NetworkFeeEvidence nativeSymbol(@javax.annotation.Nullable String nativeSymbol) {
    this.nativeSymbol = nativeSymbol;
    return this;
  }

  /**
   * Get nativeSymbol
   * @return nativeSymbol
   */
  @javax.annotation.Nullable
  public String getNativeSymbol() {
    return nativeSymbol;
  }

  public void setNativeSymbol(@javax.annotation.Nullable String nativeSymbol) {
    this.nativeSymbol = nativeSymbol;
  }


  public NetworkFeeEvidence nativeDecimals(@javax.annotation.Nullable Integer nativeDecimals) {
    this.nativeDecimals = nativeDecimals;
    return this;
  }

  /**
   * Get nativeDecimals
   * minimum: 0
   * maximum: 30
   * @return nativeDecimals
   */
  @javax.annotation.Nullable
  public Integer getNativeDecimals() {
    return nativeDecimals;
  }

  public void setNativeDecimals(@javax.annotation.Nullable Integer nativeDecimals) {
    this.nativeDecimals = nativeDecimals;
  }


  public NetworkFeeEvidence nativeFeeObservations(@javax.annotation.Nullable List<NativeFeeObservationEvidence> nativeFeeObservations) {
    this.nativeFeeObservations = nativeFeeObservations;
    return this;
  }

  public NetworkFeeEvidence addNativeFeeObservationsItem(NativeFeeObservationEvidence nativeFeeObservationsItem) {
    if (this.nativeFeeObservations == null) {
      this.nativeFeeObservations = new ArrayList<>();
    }
    this.nativeFeeObservations.add(nativeFeeObservationsItem);
    return this;
  }

  /**
   * Get nativeFeeObservations
   * @return nativeFeeObservations
   */
  @javax.annotation.Nullable
  public List<NativeFeeObservationEvidence> getNativeFeeObservations() {
    return nativeFeeObservations;
  }

  public void setNativeFeeObservations(@javax.annotation.Nullable List<NativeFeeObservationEvidence> nativeFeeObservations) {
    this.nativeFeeObservations = nativeFeeObservations;
  }


  public NetworkFeeEvidence nativeUsdObservations(@javax.annotation.Nullable List<NativeUsdObservationEvidence> nativeUsdObservations) {
    this.nativeUsdObservations = nativeUsdObservations;
    return this;
  }

  public NetworkFeeEvidence addNativeUsdObservationsItem(NativeUsdObservationEvidence nativeUsdObservationsItem) {
    if (this.nativeUsdObservations == null) {
      this.nativeUsdObservations = new ArrayList<>();
    }
    this.nativeUsdObservations.add(nativeUsdObservationsItem);
    return this;
  }

  /**
   * Get nativeUsdObservations
   * @return nativeUsdObservations
   */
  @javax.annotation.Nullable
  public List<NativeUsdObservationEvidence> getNativeUsdObservations() {
    return nativeUsdObservations;
  }

  public void setNativeUsdObservations(@javax.annotation.Nullable List<NativeUsdObservationEvidence> nativeUsdObservations) {
    this.nativeUsdObservations = nativeUsdObservations;
  }


  public NetworkFeeEvidence expiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the NetworkFeeEvidence instance itself
   */
  public NetworkFeeEvidence putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkFeeEvidence networkFeeEvidence = (NetworkFeeEvidence) o;
    return Objects.equals(this.type, networkFeeEvidence.type) &&
        Objects.equals(this.version, networkFeeEvidence.version) &&
        Objects.equals(this.network, networkFeeEvidence.network) &&
        Objects.equals(this.assetId, networkFeeEvidence.assetId) &&
        Objects.equals(this.payloadProfile, networkFeeEvidence.payloadProfile) &&
        Objects.equals(this.nativeSymbol, networkFeeEvidence.nativeSymbol) &&
        Objects.equals(this.nativeDecimals, networkFeeEvidence.nativeDecimals) &&
        Objects.equals(this.nativeFeeObservations, networkFeeEvidence.nativeFeeObservations) &&
        Objects.equals(this.nativeUsdObservations, networkFeeEvidence.nativeUsdObservations) &&
        Objects.equals(this.expiresAt, networkFeeEvidence.expiresAt)&&
        Objects.equals(this.additionalProperties, networkFeeEvidence.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, version, network, assetId, payloadProfile, nativeSymbol, nativeDecimals, nativeFeeObservations, nativeUsdObservations, expiresAt, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkFeeEvidence {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    payloadProfile: ").append(toIndentedString(payloadProfile)).append("\n");
    sb.append("    nativeSymbol: ").append(toIndentedString(nativeSymbol)).append("\n");
    sb.append("    nativeDecimals: ").append(toIndentedString(nativeDecimals)).append("\n");
    sb.append("    nativeFeeObservations: ").append(toIndentedString(nativeFeeObservations)).append("\n");
    sb.append("    nativeUsdObservations: ").append(toIndentedString(nativeUsdObservations)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "version", "network", "assetId", "payloadProfile", "nativeSymbol", "nativeDecimals", "nativeFeeObservations", "nativeUsdObservations", "expiresAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "version", "network", "assetId", "payloadProfile"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NetworkFeeEvidence
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NetworkFeeEvidence.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in NetworkFeeEvidence is not found in the empty JSON string", NetworkFeeEvidence.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NetworkFeeEvidence.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network").toString()));
      }
      if (!jsonObj.get("assetId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `assetId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assetId").toString()));
      }
      if (!jsonObj.get("payloadProfile").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payloadProfile` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payloadProfile").toString()));
      }
      if ((jsonObj.get("nativeSymbol") != null && !jsonObj.get("nativeSymbol").isJsonNull()) && !jsonObj.get("nativeSymbol").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nativeSymbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nativeSymbol").toString()));
      }
      if (jsonObj.get("nativeFeeObservations") != null && !jsonObj.get("nativeFeeObservations").isJsonNull()) {
        JsonArray jsonArraynativeFeeObservations = jsonObj.getAsJsonArray("nativeFeeObservations");
        if (jsonArraynativeFeeObservations != null) {
          // ensure the json data is an array
          if (!jsonObj.get("nativeFeeObservations").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nativeFeeObservations` to be an array in the JSON string but got `%s`", jsonObj.get("nativeFeeObservations").toString()));
          }

          // validate the optional field `nativeFeeObservations` (array)
          for (int i = 0; i < jsonArraynativeFeeObservations.size(); i++) {
            NativeFeeObservationEvidence.validateJsonElement(jsonArraynativeFeeObservations.get(i));
          };
        }
      }
      if (jsonObj.get("nativeUsdObservations") != null && !jsonObj.get("nativeUsdObservations").isJsonNull()) {
        JsonArray jsonArraynativeUsdObservations = jsonObj.getAsJsonArray("nativeUsdObservations");
        if (jsonArraynativeUsdObservations != null) {
          // ensure the json data is an array
          if (!jsonObj.get("nativeUsdObservations").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nativeUsdObservations` to be an array in the JSON string but got `%s`", jsonObj.get("nativeUsdObservations").toString()));
          }

          // validate the optional field `nativeUsdObservations` (array)
          for (int i = 0; i < jsonArraynativeUsdObservations.size(); i++) {
            NativeUsdObservationEvidence.validateJsonElement(jsonArraynativeUsdObservations.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NetworkFeeEvidence.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NetworkFeeEvidence' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NetworkFeeEvidence> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NetworkFeeEvidence.class));

       return (TypeAdapter<T>) new TypeAdapter<NetworkFeeEvidence>() {
           @Override
           public void write(JsonWriter out, NetworkFeeEvidence value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public NetworkFeeEvidence read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             NetworkFeeEvidence instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NetworkFeeEvidence given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NetworkFeeEvidence
   * @throws IOException if the JSON string is invalid with respect to NetworkFeeEvidence
   */
  public static NetworkFeeEvidence fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NetworkFeeEvidence.class);
  }

  /**
   * Convert an instance of NetworkFeeEvidence to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
