/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.x402api.client.model.FeePolicyDocument;
import com.x402api.client.model.NetworkFeeAlternative;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.x402api.client.core.JSON;

/**
 * NetworkFeePreviewResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class NetworkFeePreviewResponse {
  public static final String SERIALIZED_NAME_FEE_POLICY = "fee_policy";
  @SerializedName(SERIALIZED_NAME_FEE_POLICY)
  @javax.annotation.Nonnull
  private FeePolicyDocument feePolicy;

  public static final String SERIALIZED_NAME_ALTERNATIVES = "alternatives";
  @SerializedName(SERIALIZED_NAME_ALTERNATIVES)
  @javax.annotation.Nonnull
  private List<NetworkFeeAlternative> alternatives = new ArrayList<>();

  public static final String SERIALIZED_NAME_FEE_QUOTE_DIGEST = "fee_quote_digest";
  @SerializedName(SERIALIZED_NAME_FEE_QUOTE_DIGEST)
  @javax.annotation.Nonnull
  private String feeQuoteDigest;

  public NetworkFeePreviewResponse() {
  }

  public NetworkFeePreviewResponse feePolicy(@javax.annotation.Nonnull FeePolicyDocument feePolicy) {
    this.feePolicy = feePolicy;
    return this;
  }

  /**
   * Get feePolicy
   * @return feePolicy
   */
  @javax.annotation.Nonnull
  public FeePolicyDocument getFeePolicy() {
    return feePolicy;
  }

  public void setFeePolicy(@javax.annotation.Nonnull FeePolicyDocument feePolicy) {
    this.feePolicy = feePolicy;
  }


  public NetworkFeePreviewResponse alternatives(@javax.annotation.Nonnull List<NetworkFeeAlternative> alternatives) {
    this.alternatives = alternatives;
    return this;
  }

  public NetworkFeePreviewResponse addAlternativesItem(NetworkFeeAlternative alternativesItem) {
    if (this.alternatives == null) {
      this.alternatives = new ArrayList<>();
    }
    this.alternatives.add(alternativesItem);
    return this;
  }

  /**
   * Get alternatives
   * @return alternatives
   */
  @javax.annotation.Nonnull
  public List<NetworkFeeAlternative> getAlternatives() {
    return alternatives;
  }

  public void setAlternatives(@javax.annotation.Nonnull List<NetworkFeeAlternative> alternatives) {
    this.alternatives = alternatives;
  }


  public NetworkFeePreviewResponse feeQuoteDigest(@javax.annotation.Nonnull String feeQuoteDigest) {
    this.feeQuoteDigest = feeQuoteDigest;
    return this;
  }

  /**
   * Get feeQuoteDigest
   * @return feeQuoteDigest
   */
  @javax.annotation.Nonnull
  public String getFeeQuoteDigest() {
    return feeQuoteDigest;
  }

  public void setFeeQuoteDigest(@javax.annotation.Nonnull String feeQuoteDigest) {
    this.feeQuoteDigest = feeQuoteDigest;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the NetworkFeePreviewResponse instance itself
   */
  public NetworkFeePreviewResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkFeePreviewResponse networkFeePreviewResponse = (NetworkFeePreviewResponse) o;
    return Objects.equals(this.feePolicy, networkFeePreviewResponse.feePolicy) &&
        Objects.equals(this.alternatives, networkFeePreviewResponse.alternatives) &&
        Objects.equals(this.feeQuoteDigest, networkFeePreviewResponse.feeQuoteDigest)&&
        Objects.equals(this.additionalProperties, networkFeePreviewResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feePolicy, alternatives, feeQuoteDigest, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkFeePreviewResponse {\n");
    sb.append("    feePolicy: ").append(toIndentedString(feePolicy)).append("\n");
    sb.append("    alternatives: ").append(toIndentedString(alternatives)).append("\n");
    sb.append("    feeQuoteDigest: ").append(toIndentedString(feeQuoteDigest)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("fee_policy", "alternatives", "fee_quote_digest"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("fee_policy", "alternatives", "fee_quote_digest"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NetworkFeePreviewResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NetworkFeePreviewResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in NetworkFeePreviewResponse is not found in the empty JSON string", NetworkFeePreviewResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NetworkFeePreviewResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `fee_policy`
      FeePolicyDocument.validateJsonElement(jsonObj.get("fee_policy"));
      if (jsonObj.get("alternatives") != null) {
        if (!jsonObj.get("alternatives").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `alternatives` to be an array in the JSON string but got `%s`", jsonObj.get("alternatives").toString()));
        }
        JsonArray jsonArrayalternatives = jsonObj.getAsJsonArray("alternatives");
        // validate the required field `alternatives` (array)
        for (int i = 0; i < jsonArrayalternatives.size(); i++) {
          NetworkFeeAlternative.validateJsonElement(jsonArrayalternatives.get(i));
        }
      }
      if (!jsonObj.get("fee_quote_digest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fee_quote_digest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fee_quote_digest").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NetworkFeePreviewResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NetworkFeePreviewResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NetworkFeePreviewResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NetworkFeePreviewResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<NetworkFeePreviewResponse>() {
           @Override
           public void write(JsonWriter out, NetworkFeePreviewResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public NetworkFeePreviewResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             NetworkFeePreviewResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NetworkFeePreviewResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NetworkFeePreviewResponse
   * @throws IOException if the JSON string is invalid with respect to NetworkFeePreviewResponse
   */
  public static NetworkFeePreviewResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NetworkFeePreviewResponse.class);
  }

  /**
   * Convert an instance of NetworkFeePreviewResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
