/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * * &#x60;created&#x60; - Created * &#x60;payment_pending&#x60; - Payment pending * &#x60;paid&#x60; - Paid * &#x60;fulfillment_pending&#x60; - Fulfillment pending * &#x60;fulfilled&#x60; - Fulfilled * &#x60;expired&#x60; - Expired * &#x60;failed&#x60; - Failed
 */
@JsonAdapter(OrderStatusEnum.Adapter.class)
public enum OrderStatusEnum {

  CREATED("created"),

  PAYMENT_PENDING("payment_pending"),

  PAID("paid"),

  FULFILLMENT_PENDING("fulfillment_pending"),

  FULFILLED("fulfilled"),

  EXPIRED("expired"),

  FAILED("failed"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  OrderStatusEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OrderStatusEnum fromValue(String value) {
    for (OrderStatusEnum b : OrderStatusEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<OrderStatusEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final OrderStatusEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OrderStatusEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OrderStatusEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    OrderStatusEnum.fromValue(value);
  }
}
