/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * * &#x60;accepting&#x60; - accepting * &#x60;setup_required&#x60; - setup_required * &#x60;temporarily_unavailable&#x60; - temporarily_unavailable * &#x60;paused_by_tenant&#x60; - paused_by_tenant
 */
@JsonAdapter(PaymentReadinessStateEnum.Adapter.class)
public enum PaymentReadinessStateEnum {

  ACCEPTING("accepting"),

  SETUP_REQUIRED("setup_required"),

  TEMPORARILY_UNAVAILABLE("temporarily_unavailable"),

  PAUSED_BY_TENANT("paused_by_tenant"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  PaymentReadinessStateEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentReadinessStateEnum fromValue(String value) {
    for (PaymentReadinessStateEnum b : PaymentReadinessStateEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<PaymentReadinessStateEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentReadinessStateEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentReadinessStateEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentReadinessStateEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PaymentReadinessStateEnum.fromValue(value);
  }
}
