/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.x402api.client.model.FeePolicyDocument;
import com.x402api.client.model.NetworkFeeAlternative;
import com.x402api.client.model.NetworkFeeEvidence;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.x402api.client.core.JSON;

/**
 * PaymentReceipt
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PaymentReceipt {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private UUID id;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  @javax.annotation.Nonnull
  private UUID orderId;

  public static final String SERIALIZED_NAME_SETTLEMENT_JOB_ID = "settlement_job_id";
  @SerializedName(SERIALIZED_NAME_SETTLEMENT_JOB_ID)
  @javax.annotation.Nonnull
  private UUID settlementJobId;

  public static final String SERIALIZED_NAME_RECEIPT = "receipt";
  @SerializedName(SERIALIZED_NAME_RECEIPT)
  @javax.annotation.Nullable
  private Object receipt = null;

  public static final String SERIALIZED_NAME_RECEIPT_DIGEST = "receipt_digest";
  @SerializedName(SERIALIZED_NAME_RECEIPT_DIGEST)
  @javax.annotation.Nonnull
  private String receiptDigest;

  public static final String SERIALIZED_NAME_SIGNATURE = "signature";
  @SerializedName(SERIALIZED_NAME_SIGNATURE)
  @javax.annotation.Nonnull
  private String signature;

  public static final String SERIALIZED_NAME_SIGNING_KEY_VERSION = "signing_key_version";
  @SerializedName(SERIALIZED_NAME_SIGNING_KEY_VERSION)
  @javax.annotation.Nonnull
  private String signingKeyVersion;

  public static final String SERIALIZED_NAME_ELIGIBLE_ALTERNATIVES = "eligible_alternatives";
  @SerializedName(SERIALIZED_NAME_ELIGIBLE_ALTERNATIVES)
  @javax.annotation.Nonnull
  private List<NetworkFeeAlternative> eligibleAlternatives = new ArrayList<>();

  public static final String SERIALIZED_NAME_FEE_POLICY = "fee_policy";
  @SerializedName(SERIALIZED_NAME_FEE_POLICY)
  @javax.annotation.Nullable
  private FeePolicyDocument feePolicy;

  public static final String SERIALIZED_NAME_FEE_EVIDENCE = "fee_evidence";
  @SerializedName(SERIALIZED_NAME_FEE_EVIDENCE)
  @javax.annotation.Nullable
  private NetworkFeeEvidence feeEvidence;

  public static final String SERIALIZED_NAME_FEE_QUOTE_DIGEST = "fee_quote_digest";
  @SerializedName(SERIALIZED_NAME_FEE_QUOTE_DIGEST)
  @javax.annotation.Nullable
  private String feeQuoteDigest;

  public static final String SERIALIZED_NAME_FEE_QUOTE_EXPIRES_AT = "fee_quote_expires_at";
  @SerializedName(SERIALIZED_NAME_FEE_QUOTE_EXPIRES_AT)
  @javax.annotation.Nullable
  private OffsetDateTime feeQuoteExpiresAt;

  public static final String SERIALIZED_NAME_SETTLEMENT_AMOUNT_ATOMIC = "settlement_amount_atomic";
  @SerializedName(SERIALIZED_NAME_SETTLEMENT_AMOUNT_ATOMIC)
  @javax.annotation.Nonnull
  private String settlementAmountAtomic;

  public static final String SERIALIZED_NAME_GAS_MODE = "gas_mode";
  @SerializedName(SERIALIZED_NAME_GAS_MODE)
  @javax.annotation.Nonnull
  private String gasMode;

  public static final String SERIALIZED_NAME_BUYER_NATIVE_FEE_ATOMIC = "buyer_native_fee_atomic";
  @SerializedName(SERIALIZED_NAME_BUYER_NATIVE_FEE_ATOMIC)
  @javax.annotation.Nullable
  private String buyerNativeFeeAtomic;

  public static final String SERIALIZED_NAME_SPONSORED_NATIVE_FEE_ATOMIC = "sponsored_native_fee_atomic";
  @SerializedName(SERIALIZED_NAME_SPONSORED_NATIVE_FEE_ATOMIC)
  @javax.annotation.Nullable
  private String sponsoredNativeFeeAtomic;

  public static final String SERIALIZED_NAME_SPONSORED_NATIVE_SYMBOL = "sponsored_native_symbol";
  @SerializedName(SERIALIZED_NAME_SPONSORED_NATIVE_SYMBOL)
  @javax.annotation.Nullable
  private String sponsoredNativeSymbol;

  public static final String SERIALIZED_NAME_TENANT_GAS_CHARGE_MICROS = "tenant_gas_charge_micros";
  @SerializedName(SERIALIZED_NAME_TENANT_GAS_CHARGE_MICROS)
  @javax.annotation.Nullable
  private String tenantGasChargeMicros;

  public static final String SERIALIZED_NAME_GAS_SPONSORSHIP_EVIDENCE_DIGEST = "gas_sponsorship_evidence_digest";
  @SerializedName(SERIALIZED_NAME_GAS_SPONSORSHIP_EVIDENCE_DIGEST)
  @javax.annotation.Nullable
  private String gasSponsorshipEvidenceDigest;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public PaymentReceipt() {
  }

  public PaymentReceipt(
     UUID id,
     UUID orderId,
     UUID settlementJobId,
     Object receipt,
     String receiptDigest,
     String signature,
     String signingKeyVersion,
     List<NetworkFeeAlternative> eligibleAlternatives,
     FeePolicyDocument feePolicy,
     NetworkFeeEvidence feeEvidence,
     String feeQuoteDigest,
     OffsetDateTime feeQuoteExpiresAt,
     String settlementAmountAtomic,
     String gasMode,
     String buyerNativeFeeAtomic,
     String sponsoredNativeFeeAtomic,
     String sponsoredNativeSymbol,
     String tenantGasChargeMicros,
     String gasSponsorshipEvidenceDigest,
     OffsetDateTime createdAt
  ) {
    this();
    this.id = id;
    this.orderId = orderId;
    this.settlementJobId = settlementJobId;
    this.receipt = receipt;
    this.receiptDigest = receiptDigest;
    this.signature = signature;
    this.signingKeyVersion = signingKeyVersion;
    this.eligibleAlternatives = eligibleAlternatives;
    this.feePolicy = feePolicy;
    this.feeEvidence = feeEvidence;
    this.feeQuoteDigest = feeQuoteDigest;
    this.feeQuoteExpiresAt = feeQuoteExpiresAt;
    this.settlementAmountAtomic = settlementAmountAtomic;
    this.gasMode = gasMode;
    this.buyerNativeFeeAtomic = buyerNativeFeeAtomic;
    this.sponsoredNativeFeeAtomic = sponsoredNativeFeeAtomic;
    this.sponsoredNativeSymbol = sponsoredNativeSymbol;
    this.tenantGasChargeMicros = tenantGasChargeMicros;
    this.gasSponsorshipEvidenceDigest = gasSponsorshipEvidenceDigest;
    this.createdAt = createdAt;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public UUID getId() {
    return id;
  }



  /**
   * Get orderId
   * @return orderId
   */
  @javax.annotation.Nonnull
  public UUID getOrderId() {
    return orderId;
  }



  /**
   * Get settlementJobId
   * @return settlementJobId
   */
  @javax.annotation.Nonnull
  public UUID getSettlementJobId() {
    return settlementJobId;
  }



  /**
   * Get receipt
   * @return receipt
   */
  @javax.annotation.Nullable
  public Object getReceipt() {
    return receipt;
  }



  /**
   * Get receiptDigest
   * @return receiptDigest
   */
  @javax.annotation.Nonnull
  public String getReceiptDigest() {
    return receiptDigest;
  }



  /**
   * Get signature
   * @return signature
   */
  @javax.annotation.Nonnull
  public String getSignature() {
    return signature;
  }



  /**
   * Get signingKeyVersion
   * @return signingKeyVersion
   */
  @javax.annotation.Nonnull
  public String getSigningKeyVersion() {
    return signingKeyVersion;
  }



  /**
   * Get eligibleAlternatives
   * @return eligibleAlternatives
   */
  @javax.annotation.Nonnull
  public List<NetworkFeeAlternative> getEligibleAlternatives() {
    return eligibleAlternatives;
  }



  /**
   * Get feePolicy
   * @return feePolicy
   */
  @javax.annotation.Nullable
  public FeePolicyDocument getFeePolicy() {
    return feePolicy;
  }



  /**
   * Get feeEvidence
   * @return feeEvidence
   */
  @javax.annotation.Nullable
  public NetworkFeeEvidence getFeeEvidence() {
    return feeEvidence;
  }



  /**
   * Get feeQuoteDigest
   * @return feeQuoteDigest
   */
  @javax.annotation.Nullable
  public String getFeeQuoteDigest() {
    return feeQuoteDigest;
  }



  /**
   * Get feeQuoteExpiresAt
   * @return feeQuoteExpiresAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getFeeQuoteExpiresAt() {
    return feeQuoteExpiresAt;
  }



  /**
   * Get settlementAmountAtomic
   * @return settlementAmountAtomic
   */
  @javax.annotation.Nonnull
  public String getSettlementAmountAtomic() {
    return settlementAmountAtomic;
  }



  /**
   * Get gasMode
   * @return gasMode
   */
  @javax.annotation.Nonnull
  public String getGasMode() {
    return gasMode;
  }



  /**
   * Get buyerNativeFeeAtomic
   * @return buyerNativeFeeAtomic
   */
  @javax.annotation.Nullable
  public String getBuyerNativeFeeAtomic() {
    return buyerNativeFeeAtomic;
  }



  /**
   * Get sponsoredNativeFeeAtomic
   * @return sponsoredNativeFeeAtomic
   */
  @javax.annotation.Nullable
  public String getSponsoredNativeFeeAtomic() {
    return sponsoredNativeFeeAtomic;
  }



  /**
   * Get sponsoredNativeSymbol
   * @return sponsoredNativeSymbol
   */
  @javax.annotation.Nullable
  public String getSponsoredNativeSymbol() {
    return sponsoredNativeSymbol;
  }



  /**
   * Get tenantGasChargeMicros
   * @return tenantGasChargeMicros
   */
  @javax.annotation.Nullable
  public String getTenantGasChargeMicros() {
    return tenantGasChargeMicros;
  }



  /**
   * Get gasSponsorshipEvidenceDigest
   * @return gasSponsorshipEvidenceDigest
   */
  @javax.annotation.Nullable
  public String getGasSponsorshipEvidenceDigest() {
    return gasSponsorshipEvidenceDigest;
  }



  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentReceipt instance itself
   */
  public PaymentReceipt putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentReceipt paymentReceipt = (PaymentReceipt) o;
    return Objects.equals(this.id, paymentReceipt.id) &&
        Objects.equals(this.orderId, paymentReceipt.orderId) &&
        Objects.equals(this.settlementJobId, paymentReceipt.settlementJobId) &&
        Objects.equals(this.receipt, paymentReceipt.receipt) &&
        Objects.equals(this.receiptDigest, paymentReceipt.receiptDigest) &&
        Objects.equals(this.signature, paymentReceipt.signature) &&
        Objects.equals(this.signingKeyVersion, paymentReceipt.signingKeyVersion) &&
        Objects.equals(this.eligibleAlternatives, paymentReceipt.eligibleAlternatives) &&
        Objects.equals(this.feePolicy, paymentReceipt.feePolicy) &&
        Objects.equals(this.feeEvidence, paymentReceipt.feeEvidence) &&
        Objects.equals(this.feeQuoteDigest, paymentReceipt.feeQuoteDigest) &&
        Objects.equals(this.feeQuoteExpiresAt, paymentReceipt.feeQuoteExpiresAt) &&
        Objects.equals(this.settlementAmountAtomic, paymentReceipt.settlementAmountAtomic) &&
        Objects.equals(this.gasMode, paymentReceipt.gasMode) &&
        Objects.equals(this.buyerNativeFeeAtomic, paymentReceipt.buyerNativeFeeAtomic) &&
        Objects.equals(this.sponsoredNativeFeeAtomic, paymentReceipt.sponsoredNativeFeeAtomic) &&
        Objects.equals(this.sponsoredNativeSymbol, paymentReceipt.sponsoredNativeSymbol) &&
        Objects.equals(this.tenantGasChargeMicros, paymentReceipt.tenantGasChargeMicros) &&
        Objects.equals(this.gasSponsorshipEvidenceDigest, paymentReceipt.gasSponsorshipEvidenceDigest) &&
        Objects.equals(this.createdAt, paymentReceipt.createdAt)&&
        Objects.equals(this.additionalProperties, paymentReceipt.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, orderId, settlementJobId, receipt, receiptDigest, signature, signingKeyVersion, eligibleAlternatives, feePolicy, feeEvidence, feeQuoteDigest, feeQuoteExpiresAt, settlementAmountAtomic, gasMode, buyerNativeFeeAtomic, sponsoredNativeFeeAtomic, sponsoredNativeSymbol, tenantGasChargeMicros, gasSponsorshipEvidenceDigest, createdAt, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentReceipt {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    settlementJobId: ").append(toIndentedString(settlementJobId)).append("\n");
    sb.append("    receipt: ").append(toIndentedString(receipt)).append("\n");
    sb.append("    receiptDigest: ").append(toIndentedString(receiptDigest)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    signingKeyVersion: ").append(toIndentedString(signingKeyVersion)).append("\n");
    sb.append("    eligibleAlternatives: ").append(toIndentedString(eligibleAlternatives)).append("\n");
    sb.append("    feePolicy: ").append(toIndentedString(feePolicy)).append("\n");
    sb.append("    feeEvidence: ").append(toIndentedString(feeEvidence)).append("\n");
    sb.append("    feeQuoteDigest: ").append(toIndentedString(feeQuoteDigest)).append("\n");
    sb.append("    feeQuoteExpiresAt: ").append(toIndentedString(feeQuoteExpiresAt)).append("\n");
    sb.append("    settlementAmountAtomic: ").append(toIndentedString(settlementAmountAtomic)).append("\n");
    sb.append("    gasMode: ").append(toIndentedString(gasMode)).append("\n");
    sb.append("    buyerNativeFeeAtomic: ").append(toIndentedString(buyerNativeFeeAtomic)).append("\n");
    sb.append("    sponsoredNativeFeeAtomic: ").append(toIndentedString(sponsoredNativeFeeAtomic)).append("\n");
    sb.append("    sponsoredNativeSymbol: ").append(toIndentedString(sponsoredNativeSymbol)).append("\n");
    sb.append("    tenantGasChargeMicros: ").append(toIndentedString(tenantGasChargeMicros)).append("\n");
    sb.append("    gasSponsorshipEvidenceDigest: ").append(toIndentedString(gasSponsorshipEvidenceDigest)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "order_id", "settlement_job_id", "receipt", "receipt_digest", "signature", "signing_key_version", "eligible_alternatives", "fee_policy", "fee_evidence", "fee_quote_digest", "fee_quote_expires_at", "settlement_amount_atomic", "gas_mode", "buyer_native_fee_atomic", "sponsored_native_fee_atomic", "sponsored_native_symbol", "tenant_gas_charge_micros", "gas_sponsorship_evidence_digest", "created_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "order_id", "settlement_job_id", "receipt", "receipt_digest", "signature", "signing_key_version", "eligible_alternatives", "fee_policy", "fee_evidence", "fee_quote_digest", "fee_quote_expires_at", "settlement_amount_atomic", "gas_mode", "buyer_native_fee_atomic", "sponsored_native_fee_atomic", "sponsored_native_symbol", "tenant_gas_charge_micros", "gas_sponsorship_evidence_digest", "created_at"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PaymentReceipt
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentReceipt.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PaymentReceipt is not found in the empty JSON string", PaymentReceipt.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PaymentReceipt.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_id").toString()));
      }
      if (!jsonObj.get("settlement_job_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `settlement_job_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("settlement_job_id").toString()));
      }
      if (!jsonObj.get("receipt_digest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `receipt_digest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("receipt_digest").toString()));
      }
      if (!jsonObj.get("signature").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `signature` to be a primitive type in the JSON string but got `%s`", jsonObj.get("signature").toString()));
      }
      if (!jsonObj.get("signing_key_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `signing_key_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("signing_key_version").toString()));
      }
      if (jsonObj.get("eligible_alternatives") != null) {
        if (!jsonObj.get("eligible_alternatives").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `eligible_alternatives` to be an array in the JSON string but got `%s`", jsonObj.get("eligible_alternatives").toString()));
        }
        JsonArray jsonArrayeligibleAlternatives = jsonObj.getAsJsonArray("eligible_alternatives");
        // validate the required field `eligible_alternatives` (array)
        for (int i = 0; i < jsonArrayeligibleAlternatives.size(); i++) {
          NetworkFeeAlternative.validateJsonElement(jsonArrayeligibleAlternatives.get(i));
        }
      }
      if (jsonObj.get("fee_policy") != null && !jsonObj.get("fee_policy").isJsonNull()) {
      // validate the required field `fee_policy`
      FeePolicyDocument.validateJsonElement(jsonObj.get("fee_policy"));
      }
      if (jsonObj.get("fee_evidence") != null && !jsonObj.get("fee_evidence").isJsonNull()) {
      // validate the required field `fee_evidence`
      NetworkFeeEvidence.validateJsonElement(jsonObj.get("fee_evidence"));
      }
      if ((jsonObj.get("fee_quote_digest") != null && !jsonObj.get("fee_quote_digest").isJsonNull()) && !jsonObj.get("fee_quote_digest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fee_quote_digest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fee_quote_digest").toString()));
      }
      if (!jsonObj.get("settlement_amount_atomic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `settlement_amount_atomic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("settlement_amount_atomic").toString()));
      }
      if (!jsonObj.get("gas_mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `gas_mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gas_mode").toString()));
      }
      if ((jsonObj.get("buyer_native_fee_atomic") != null && !jsonObj.get("buyer_native_fee_atomic").isJsonNull()) && !jsonObj.get("buyer_native_fee_atomic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `buyer_native_fee_atomic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buyer_native_fee_atomic").toString()));
      }
      if ((jsonObj.get("sponsored_native_fee_atomic") != null && !jsonObj.get("sponsored_native_fee_atomic").isJsonNull()) && !jsonObj.get("sponsored_native_fee_atomic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sponsored_native_fee_atomic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sponsored_native_fee_atomic").toString()));
      }
      if ((jsonObj.get("sponsored_native_symbol") != null && !jsonObj.get("sponsored_native_symbol").isJsonNull()) && !jsonObj.get("sponsored_native_symbol").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sponsored_native_symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sponsored_native_symbol").toString()));
      }
      if ((jsonObj.get("tenant_gas_charge_micros") != null && !jsonObj.get("tenant_gas_charge_micros").isJsonNull()) && !jsonObj.get("tenant_gas_charge_micros").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tenant_gas_charge_micros` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenant_gas_charge_micros").toString()));
      }
      if ((jsonObj.get("gas_sponsorship_evidence_digest") != null && !jsonObj.get("gas_sponsorship_evidence_digest").isJsonNull()) && !jsonObj.get("gas_sponsorship_evidence_digest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `gas_sponsorship_evidence_digest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gas_sponsorship_evidence_digest").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentReceipt.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentReceipt' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentReceipt> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentReceipt.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentReceipt>() {
           @Override
           public void write(JsonWriter out, PaymentReceipt value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentReceipt read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             PaymentReceipt instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PaymentReceipt given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PaymentReceipt
   * @throws IOException if the JSON string is invalid with respect to PaymentReceipt
   */
  public static PaymentReceipt fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentReceipt.class);
  }

  /**
   * Convert an instance of PaymentReceipt to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
