/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.x402api.client.model.PaymentReadinessAsset;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.x402api.client.core.JSON;

/**
 * PaymentReadinessRail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PaymentReadinessRail {
  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  @javax.annotation.Nonnull
  private String network;

  public static final String SERIALIZED_NAME_TENANT_CHALLENGES_ENABLED = "tenant_challenges_enabled";
  @SerializedName(SERIALIZED_NAME_TENANT_CHALLENGES_ENABLED)
  @javax.annotation.Nonnull
  private Boolean tenantChallengesEnabled;

  public static final String SERIALIZED_NAME_TENANT_SETTLEMENT_ENABLED = "tenant_settlement_enabled";
  @SerializedName(SERIALIZED_NAME_TENANT_SETTLEMENT_ENABLED)
  @javax.annotation.Nonnull
  private Boolean tenantSettlementEnabled;

  public static final String SERIALIZED_NAME_NETWORK_ASSISTANCE_ENABLED = "network_assistance_enabled";
  @SerializedName(SERIALIZED_NAME_NETWORK_ASSISTANCE_ENABLED)
  @javax.annotation.Nonnull
  private Boolean networkAssistanceEnabled;

  public static final String SERIALIZED_NAME_CHALLENGE_CONTROL_READY = "challenge_control_ready";
  @SerializedName(SERIALIZED_NAME_CHALLENGE_CONTROL_READY)
  @javax.annotation.Nonnull
  private Boolean challengeControlReady;

  public static final String SERIALIZED_NAME_SETTLEMENT_CONTROL_READY = "settlement_control_ready";
  @SerializedName(SERIALIZED_NAME_SETTLEMENT_CONTROL_READY)
  @javax.annotation.Nonnull
  private Boolean settlementControlReady;

  public static final String SERIALIZED_NAME_ASSETS = "assets";
  @SerializedName(SERIALIZED_NAME_ASSETS)
  @javax.annotation.Nonnull
  private List<PaymentReadinessAsset> assets = new ArrayList<>();

  public PaymentReadinessRail() {
  }

  public PaymentReadinessRail(
     String network,
     Boolean tenantChallengesEnabled,
     Boolean tenantSettlementEnabled,
     Boolean networkAssistanceEnabled,
     Boolean challengeControlReady,
     Boolean settlementControlReady,
     List<PaymentReadinessAsset> assets
  ) {
    this();
    this.network = network;
    this.tenantChallengesEnabled = tenantChallengesEnabled;
    this.tenantSettlementEnabled = tenantSettlementEnabled;
    this.networkAssistanceEnabled = networkAssistanceEnabled;
    this.challengeControlReady = challengeControlReady;
    this.settlementControlReady = settlementControlReady;
    this.assets = assets;
  }

  /**
   * Get network
   * @return network
   */
  @javax.annotation.Nonnull
  public String getNetwork() {
    return network;
  }



  /**
   * Get tenantChallengesEnabled
   * @return tenantChallengesEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getTenantChallengesEnabled() {
    return tenantChallengesEnabled;
  }



  /**
   * Get tenantSettlementEnabled
   * @return tenantSettlementEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getTenantSettlementEnabled() {
    return tenantSettlementEnabled;
  }



  /**
   * Get networkAssistanceEnabled
   * @return networkAssistanceEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getNetworkAssistanceEnabled() {
    return networkAssistanceEnabled;
  }



  /**
   * Get challengeControlReady
   * @return challengeControlReady
   */
  @javax.annotation.Nonnull
  public Boolean getChallengeControlReady() {
    return challengeControlReady;
  }



  /**
   * Get settlementControlReady
   * @return settlementControlReady
   */
  @javax.annotation.Nonnull
  public Boolean getSettlementControlReady() {
    return settlementControlReady;
  }



  /**
   * Get assets
   * @return assets
   */
  @javax.annotation.Nonnull
  public List<PaymentReadinessAsset> getAssets() {
    return assets;
  }


  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PaymentReadinessRail instance itself
   */
  public PaymentReadinessRail putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentReadinessRail paymentReadinessRail = (PaymentReadinessRail) o;
    return Objects.equals(this.network, paymentReadinessRail.network) &&
        Objects.equals(this.tenantChallengesEnabled, paymentReadinessRail.tenantChallengesEnabled) &&
        Objects.equals(this.tenantSettlementEnabled, paymentReadinessRail.tenantSettlementEnabled) &&
        Objects.equals(this.networkAssistanceEnabled, paymentReadinessRail.networkAssistanceEnabled) &&
        Objects.equals(this.challengeControlReady, paymentReadinessRail.challengeControlReady) &&
        Objects.equals(this.settlementControlReady, paymentReadinessRail.settlementControlReady) &&
        Objects.equals(this.assets, paymentReadinessRail.assets)&&
        Objects.equals(this.additionalProperties, paymentReadinessRail.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(network, tenantChallengesEnabled, tenantSettlementEnabled, networkAssistanceEnabled, challengeControlReady, settlementControlReady, assets, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentReadinessRail {\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    tenantChallengesEnabled: ").append(toIndentedString(tenantChallengesEnabled)).append("\n");
    sb.append("    tenantSettlementEnabled: ").append(toIndentedString(tenantSettlementEnabled)).append("\n");
    sb.append("    networkAssistanceEnabled: ").append(toIndentedString(networkAssistanceEnabled)).append("\n");
    sb.append("    challengeControlReady: ").append(toIndentedString(challengeControlReady)).append("\n");
    sb.append("    settlementControlReady: ").append(toIndentedString(settlementControlReady)).append("\n");
    sb.append("    assets: ").append(toIndentedString(assets)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("network", "tenant_challenges_enabled", "tenant_settlement_enabled", "network_assistance_enabled", "challenge_control_ready", "settlement_control_ready", "assets"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("network", "tenant_challenges_enabled", "tenant_settlement_enabled", "network_assistance_enabled", "challenge_control_ready", "settlement_control_ready", "assets"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PaymentReadinessRail
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentReadinessRail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PaymentReadinessRail is not found in the empty JSON string", PaymentReadinessRail.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PaymentReadinessRail.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network").toString()));
      }
      if (jsonObj.get("assets") != null) {
        if (!jsonObj.get("assets").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `assets` to be an array in the JSON string but got `%s`", jsonObj.get("assets").toString()));
        }
        JsonArray jsonArrayassets = jsonObj.getAsJsonArray("assets");
        // validate the required field `assets` (array)
        for (int i = 0; i < jsonArrayassets.size(); i++) {
          PaymentReadinessAsset.validateJsonElement(jsonArrayassets.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentReadinessRail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentReadinessRail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentReadinessRail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentReadinessRail.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentReadinessRail>() {
           @Override
           public void write(JsonWriter out, PaymentReadinessRail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentReadinessRail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             PaymentReadinessRail instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PaymentReadinessRail given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PaymentReadinessRail
   * @throws IOException if the JSON string is invalid with respect to PaymentReadinessRail
   */
  public static PaymentReadinessRail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentReadinessRail.class);
  }

  /**
   * Convert an instance of PaymentReadinessRail to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
