/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.x402api.client.model.GasModeEnum;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.x402api.client.core.JSON;

/**
 * PublicNetworkFeeAlternative
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PublicNetworkFeeAlternative {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nonnull
  private Integer version;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  @javax.annotation.Nonnull
  private String network;

  public static final String SERIALIZED_NAME_ASSET_ID = "assetId";
  @SerializedName(SERIALIZED_NAME_ASSET_ID)
  @javax.annotation.Nonnull
  private String assetId;

  public static final String SERIALIZED_NAME_CONTRACT_ADDRESS = "contractAddress";
  @SerializedName(SERIALIZED_NAME_CONTRACT_ADDRESS)
  @javax.annotation.Nonnull
  private String contractAddress;

  public static final String SERIALIZED_NAME_LISTED_AMOUNT_ATOMIC = "listedAmountAtomic";
  @SerializedName(SERIALIZED_NAME_LISTED_AMOUNT_ATOMIC)
  @javax.annotation.Nonnull
  private String listedAmountAtomic;

  public static final String SERIALIZED_NAME_GAS_MODE = "gasMode";
  @SerializedName(SERIALIZED_NAME_GAS_MODE)
  @javax.annotation.Nonnull
  private GasModeEnum gasMode;

  public static final String SERIALIZED_NAME_BUYER_NATIVE_FEE_ATOMIC = "buyerNativeFeeAtomic";
  @SerializedName(SERIALIZED_NAME_BUYER_NATIVE_FEE_ATOMIC)
  @javax.annotation.Nullable
  private String buyerNativeFeeAtomic;

  public static final String SERIALIZED_NAME_BUYER_PAYMENT_ATOMIC = "buyerPaymentAtomic";
  @SerializedName(SERIALIZED_NAME_BUYER_PAYMENT_ATOMIC)
  @javax.annotation.Nonnull
  private String buyerPaymentAtomic;

  public static final String SERIALIZED_NAME_TENANT_PROCEEDS_ATOMIC = "tenantProceedsAtomic";
  @SerializedName(SERIALIZED_NAME_TENANT_PROCEEDS_ATOMIC)
  @javax.annotation.Nonnull
  private String tenantProceedsAtomic;

  public static final String SERIALIZED_NAME_QUOTE_EXPIRES_AT = "quoteExpiresAt";
  @SerializedName(SERIALIZED_NAME_QUOTE_EXPIRES_AT)
  @javax.annotation.Nullable
  private OffsetDateTime quoteExpiresAt;

  public static final String SERIALIZED_NAME_ELIGIBLE = "eligible";
  @SerializedName(SERIALIZED_NAME_ELIGIBLE)
  @javax.annotation.Nonnull
  private Boolean eligible;

  public static final String SERIALIZED_NAME_EXCLUSION_REASON = "exclusionReason";
  @SerializedName(SERIALIZED_NAME_EXCLUSION_REASON)
  @javax.annotation.Nullable
  private String exclusionReason;

  public PublicNetworkFeeAlternative() {
  }

  public PublicNetworkFeeAlternative type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  public PublicNetworkFeeAlternative version(@javax.annotation.Nonnull Integer version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * minimum: 1
   * @return version
   */
  @javax.annotation.Nonnull
  public Integer getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nonnull Integer version) {
    this.version = version;
  }


  public PublicNetworkFeeAlternative network(@javax.annotation.Nonnull String network) {
    this.network = network;
    return this;
  }

  /**
   * Get network
   * @return network
   */
  @javax.annotation.Nonnull
  public String getNetwork() {
    return network;
  }

  public void setNetwork(@javax.annotation.Nonnull String network) {
    this.network = network;
  }


  public PublicNetworkFeeAlternative assetId(@javax.annotation.Nonnull String assetId) {
    this.assetId = assetId;
    return this;
  }

  /**
   * Get assetId
   * @return assetId
   */
  @javax.annotation.Nonnull
  public String getAssetId() {
    return assetId;
  }

  public void setAssetId(@javax.annotation.Nonnull String assetId) {
    this.assetId = assetId;
  }


  public PublicNetworkFeeAlternative contractAddress(@javax.annotation.Nonnull String contractAddress) {
    this.contractAddress = contractAddress;
    return this;
  }

  /**
   * Get contractAddress
   * @return contractAddress
   */
  @javax.annotation.Nonnull
  public String getContractAddress() {
    return contractAddress;
  }

  public void setContractAddress(@javax.annotation.Nonnull String contractAddress) {
    this.contractAddress = contractAddress;
  }


  public PublicNetworkFeeAlternative listedAmountAtomic(@javax.annotation.Nonnull String listedAmountAtomic) {
    this.listedAmountAtomic = listedAmountAtomic;
    return this;
  }

  /**
   * Get listedAmountAtomic
   * @return listedAmountAtomic
   */
  @javax.annotation.Nonnull
  public String getListedAmountAtomic() {
    return listedAmountAtomic;
  }

  public void setListedAmountAtomic(@javax.annotation.Nonnull String listedAmountAtomic) {
    this.listedAmountAtomic = listedAmountAtomic;
  }


  public PublicNetworkFeeAlternative gasMode(@javax.annotation.Nonnull GasModeEnum gasMode) {
    this.gasMode = gasMode;
    return this;
  }

  /**
   * Get gasMode
   * @return gasMode
   */
  @javax.annotation.Nonnull
  public GasModeEnum getGasMode() {
    return gasMode;
  }

  public void setGasMode(@javax.annotation.Nonnull GasModeEnum gasMode) {
    this.gasMode = gasMode;
  }


  public PublicNetworkFeeAlternative buyerNativeFeeAtomic(@javax.annotation.Nullable String buyerNativeFeeAtomic) {
    this.buyerNativeFeeAtomic = buyerNativeFeeAtomic;
    return this;
  }

  /**
   * Get buyerNativeFeeAtomic
   * @return buyerNativeFeeAtomic
   */
  @javax.annotation.Nullable
  public String getBuyerNativeFeeAtomic() {
    return buyerNativeFeeAtomic;
  }

  public void setBuyerNativeFeeAtomic(@javax.annotation.Nullable String buyerNativeFeeAtomic) {
    this.buyerNativeFeeAtomic = buyerNativeFeeAtomic;
  }


  public PublicNetworkFeeAlternative buyerPaymentAtomic(@javax.annotation.Nonnull String buyerPaymentAtomic) {
    this.buyerPaymentAtomic = buyerPaymentAtomic;
    return this;
  }

  /**
   * Get buyerPaymentAtomic
   * @return buyerPaymentAtomic
   */
  @javax.annotation.Nonnull
  public String getBuyerPaymentAtomic() {
    return buyerPaymentAtomic;
  }

  public void setBuyerPaymentAtomic(@javax.annotation.Nonnull String buyerPaymentAtomic) {
    this.buyerPaymentAtomic = buyerPaymentAtomic;
  }


  public PublicNetworkFeeAlternative tenantProceedsAtomic(@javax.annotation.Nonnull String tenantProceedsAtomic) {
    this.tenantProceedsAtomic = tenantProceedsAtomic;
    return this;
  }

  /**
   * Get tenantProceedsAtomic
   * @return tenantProceedsAtomic
   */
  @javax.annotation.Nonnull
  public String getTenantProceedsAtomic() {
    return tenantProceedsAtomic;
  }

  public void setTenantProceedsAtomic(@javax.annotation.Nonnull String tenantProceedsAtomic) {
    this.tenantProceedsAtomic = tenantProceedsAtomic;
  }


  public PublicNetworkFeeAlternative quoteExpiresAt(@javax.annotation.Nullable OffsetDateTime quoteExpiresAt) {
    this.quoteExpiresAt = quoteExpiresAt;
    return this;
  }

  /**
   * Get quoteExpiresAt
   * @return quoteExpiresAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getQuoteExpiresAt() {
    return quoteExpiresAt;
  }

  public void setQuoteExpiresAt(@javax.annotation.Nullable OffsetDateTime quoteExpiresAt) {
    this.quoteExpiresAt = quoteExpiresAt;
  }


  public PublicNetworkFeeAlternative eligible(@javax.annotation.Nonnull Boolean eligible) {
    this.eligible = eligible;
    return this;
  }

  /**
   * Get eligible
   * @return eligible
   */
  @javax.annotation.Nonnull
  public Boolean getEligible() {
    return eligible;
  }

  public void setEligible(@javax.annotation.Nonnull Boolean eligible) {
    this.eligible = eligible;
  }


  public PublicNetworkFeeAlternative exclusionReason(@javax.annotation.Nullable String exclusionReason) {
    this.exclusionReason = exclusionReason;
    return this;
  }

  /**
   * Get exclusionReason
   * @return exclusionReason
   */
  @javax.annotation.Nullable
  public String getExclusionReason() {
    return exclusionReason;
  }

  public void setExclusionReason(@javax.annotation.Nullable String exclusionReason) {
    this.exclusionReason = exclusionReason;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PublicNetworkFeeAlternative instance itself
   */
  public PublicNetworkFeeAlternative putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicNetworkFeeAlternative publicNetworkFeeAlternative = (PublicNetworkFeeAlternative) o;
    return Objects.equals(this.type, publicNetworkFeeAlternative.type) &&
        Objects.equals(this.version, publicNetworkFeeAlternative.version) &&
        Objects.equals(this.network, publicNetworkFeeAlternative.network) &&
        Objects.equals(this.assetId, publicNetworkFeeAlternative.assetId) &&
        Objects.equals(this.contractAddress, publicNetworkFeeAlternative.contractAddress) &&
        Objects.equals(this.listedAmountAtomic, publicNetworkFeeAlternative.listedAmountAtomic) &&
        Objects.equals(this.gasMode, publicNetworkFeeAlternative.gasMode) &&
        Objects.equals(this.buyerNativeFeeAtomic, publicNetworkFeeAlternative.buyerNativeFeeAtomic) &&
        Objects.equals(this.buyerPaymentAtomic, publicNetworkFeeAlternative.buyerPaymentAtomic) &&
        Objects.equals(this.tenantProceedsAtomic, publicNetworkFeeAlternative.tenantProceedsAtomic) &&
        Objects.equals(this.quoteExpiresAt, publicNetworkFeeAlternative.quoteExpiresAt) &&
        Objects.equals(this.eligible, publicNetworkFeeAlternative.eligible) &&
        Objects.equals(this.exclusionReason, publicNetworkFeeAlternative.exclusionReason)&&
        Objects.equals(this.additionalProperties, publicNetworkFeeAlternative.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, version, network, assetId, contractAddress, listedAmountAtomic, gasMode, buyerNativeFeeAtomic, buyerPaymentAtomic, tenantProceedsAtomic, quoteExpiresAt, eligible, exclusionReason, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicNetworkFeeAlternative {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("    listedAmountAtomic: ").append(toIndentedString(listedAmountAtomic)).append("\n");
    sb.append("    gasMode: ").append(toIndentedString(gasMode)).append("\n");
    sb.append("    buyerNativeFeeAtomic: ").append(toIndentedString(buyerNativeFeeAtomic)).append("\n");
    sb.append("    buyerPaymentAtomic: ").append(toIndentedString(buyerPaymentAtomic)).append("\n");
    sb.append("    tenantProceedsAtomic: ").append(toIndentedString(tenantProceedsAtomic)).append("\n");
    sb.append("    quoteExpiresAt: ").append(toIndentedString(quoteExpiresAt)).append("\n");
    sb.append("    eligible: ").append(toIndentedString(eligible)).append("\n");
    sb.append("    exclusionReason: ").append(toIndentedString(exclusionReason)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "version", "network", "assetId", "contractAddress", "listedAmountAtomic", "gasMode", "buyerNativeFeeAtomic", "buyerPaymentAtomic", "tenantProceedsAtomic", "quoteExpiresAt", "eligible", "exclusionReason"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "version", "network", "assetId", "contractAddress", "listedAmountAtomic", "gasMode", "buyerNativeFeeAtomic", "buyerPaymentAtomic", "tenantProceedsAtomic", "quoteExpiresAt", "eligible", "exclusionReason"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PublicNetworkFeeAlternative
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PublicNetworkFeeAlternative.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PublicNetworkFeeAlternative is not found in the empty JSON string", PublicNetworkFeeAlternative.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PublicNetworkFeeAlternative.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network").toString()));
      }
      if (!jsonObj.get("assetId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `assetId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assetId").toString()));
      }
      if (!jsonObj.get("contractAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contractAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contractAddress").toString()));
      }
      if (!jsonObj.get("listedAmountAtomic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `listedAmountAtomic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("listedAmountAtomic").toString()));
      }
      // validate the required field `gasMode`
      GasModeEnum.validateJsonElement(jsonObj.get("gasMode"));
      if ((jsonObj.get("buyerNativeFeeAtomic") != null && !jsonObj.get("buyerNativeFeeAtomic").isJsonNull()) && !jsonObj.get("buyerNativeFeeAtomic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `buyerNativeFeeAtomic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buyerNativeFeeAtomic").toString()));
      }
      if (!jsonObj.get("buyerPaymentAtomic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `buyerPaymentAtomic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buyerPaymentAtomic").toString()));
      }
      if (!jsonObj.get("tenantProceedsAtomic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tenantProceedsAtomic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantProceedsAtomic").toString()));
      }
      if ((jsonObj.get("exclusionReason") != null && !jsonObj.get("exclusionReason").isJsonNull()) && !jsonObj.get("exclusionReason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `exclusionReason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("exclusionReason").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PublicNetworkFeeAlternative.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PublicNetworkFeeAlternative' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PublicNetworkFeeAlternative> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PublicNetworkFeeAlternative.class));

       return (TypeAdapter<T>) new TypeAdapter<PublicNetworkFeeAlternative>() {
           @Override
           public void write(JsonWriter out, PublicNetworkFeeAlternative value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PublicNetworkFeeAlternative read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             PublicNetworkFeeAlternative instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PublicNetworkFeeAlternative given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PublicNetworkFeeAlternative
   * @throws IOException if the JSON string is invalid with respect to PublicNetworkFeeAlternative
   */
  public static PublicNetworkFeeAlternative fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PublicNetworkFeeAlternative.class);
  }

  /**
   * Convert an instance of PublicNetworkFeeAlternative to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
