/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.x402api.client.model.FeePolicyModeInputEnum;
import com.x402api.client.model.FeePolicyQuoteCurrencyInputEnum;
import com.x402api.client.model.HTTPMethodEnum;
import com.x402api.client.model.PriceInput;
import com.x402api.client.model.ResourceCreateFulfillmentConfig;
import com.x402api.client.model.ResourceInputFulfillmentModeEnum;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.x402api.client.core.JSON;

/**
 * ResourceCreate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ResourceCreate {
  public static final String SERIALIZED_NAME_FEE_MODE = "fee_mode";
  @SerializedName(SERIALIZED_NAME_FEE_MODE)
  @javax.annotation.Nullable
  private FeePolicyModeInputEnum feeMode;

  public static final String SERIALIZED_NAME_QUOTE_CURRENCY = "quote_currency";
  @SerializedName(SERIALIZED_NAME_QUOTE_CURRENCY)
  @javax.annotation.Nullable
  private FeePolicyQuoteCurrencyInputEnum quoteCurrency;

  public static final String SERIALIZED_NAME_FEE_ALLOWANCE_CAP_QUOTE_MICROS = "fee_allowance_cap_quote_micros";
  @SerializedName(SERIALIZED_NAME_FEE_ALLOWANCE_CAP_QUOTE_MICROS)
  @javax.annotation.Nullable
  private String feeAllowanceCapQuoteMicros = "0";

  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  @javax.annotation.Nonnull
  private String key;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  @javax.annotation.Nonnull
  private HTTPMethodEnum method;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  @javax.annotation.Nonnull
  private String path;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nonnull
  private String description;

  public static final String SERIALIZED_NAME_MIME_TYPE = "mime_type";
  @SerializedName(SERIALIZED_NAME_MIME_TYPE)
  @javax.annotation.Nullable
  private String mimeType = "application/json";

  public static final String SERIALIZED_NAME_FULFILLMENT_MODE = "fulfillment_mode";
  @SerializedName(SERIALIZED_NAME_FULFILLMENT_MODE)
  @javax.annotation.Nonnull
  private ResourceInputFulfillmentModeEnum fulfillmentMode;

  public static final String SERIALIZED_NAME_FULFILLMENT_CONFIG = "fulfillment_config";
  @SerializedName(SERIALIZED_NAME_FULFILLMENT_CONFIG)
  @javax.annotation.Nullable
  private ResourceCreateFulfillmentConfig fulfillmentConfig;

  public static final String SERIALIZED_NAME_PRICES = "prices";
  @SerializedName(SERIALIZED_NAME_PRICES)
  @javax.annotation.Nonnull
  private List<PriceInput> prices = new ArrayList<>();

  public ResourceCreate() {
  }

  public ResourceCreate feeMode(@javax.annotation.Nullable FeePolicyModeInputEnum feeMode) {
    this.feeMode = feeMode;
    return this;
  }

  /**
   * Get feeMode
   * @return feeMode
   */
  @javax.annotation.Nullable
  public FeePolicyModeInputEnum getFeeMode() {
    return feeMode;
  }

  public void setFeeMode(@javax.annotation.Nullable FeePolicyModeInputEnum feeMode) {
    this.feeMode = feeMode;
  }


  public ResourceCreate quoteCurrency(@javax.annotation.Nullable FeePolicyQuoteCurrencyInputEnum quoteCurrency) {
    this.quoteCurrency = quoteCurrency;
    return this;
  }

  /**
   * Get quoteCurrency
   * @return quoteCurrency
   */
  @javax.annotation.Nullable
  public FeePolicyQuoteCurrencyInputEnum getQuoteCurrency() {
    return quoteCurrency;
  }

  public void setQuoteCurrency(@javax.annotation.Nullable FeePolicyQuoteCurrencyInputEnum quoteCurrency) {
    this.quoteCurrency = quoteCurrency;
  }


  public ResourceCreate feeAllowanceCapQuoteMicros(@javax.annotation.Nullable String feeAllowanceCapQuoteMicros) {
    this.feeAllowanceCapQuoteMicros = feeAllowanceCapQuoteMicros;
    return this;
  }

  /**
   * Get feeAllowanceCapQuoteMicros
   * @return feeAllowanceCapQuoteMicros
   */
  @javax.annotation.Nullable
  public String getFeeAllowanceCapQuoteMicros() {
    return feeAllowanceCapQuoteMicros;
  }

  public void setFeeAllowanceCapQuoteMicros(@javax.annotation.Nullable String feeAllowanceCapQuoteMicros) {
    this.feeAllowanceCapQuoteMicros = feeAllowanceCapQuoteMicros;
  }


  public ResourceCreate key(@javax.annotation.Nonnull String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @javax.annotation.Nonnull
  public String getKey() {
    return key;
  }

  public void setKey(@javax.annotation.Nonnull String key) {
    this.key = key;
  }


  public ResourceCreate name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public ResourceCreate method(@javax.annotation.Nonnull HTTPMethodEnum method) {
    this.method = method;
    return this;
  }

  /**
   * Get method
   * @return method
   */
  @javax.annotation.Nonnull
  public HTTPMethodEnum getMethod() {
    return method;
  }

  public void setMethod(@javax.annotation.Nonnull HTTPMethodEnum method) {
    this.method = method;
  }


  public ResourceCreate path(@javax.annotation.Nonnull String path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @javax.annotation.Nonnull
  public String getPath() {
    return path;
  }

  public void setPath(@javax.annotation.Nonnull String path) {
    this.path = path;
  }


  public ResourceCreate description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public ResourceCreate mimeType(@javax.annotation.Nullable String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

  /**
   * Get mimeType
   * @return mimeType
   */
  @javax.annotation.Nullable
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(@javax.annotation.Nullable String mimeType) {
    this.mimeType = mimeType;
  }


  public ResourceCreate fulfillmentMode(@javax.annotation.Nonnull ResourceInputFulfillmentModeEnum fulfillmentMode) {
    this.fulfillmentMode = fulfillmentMode;
    return this;
  }

  /**
   * Get fulfillmentMode
   * @return fulfillmentMode
   */
  @javax.annotation.Nonnull
  public ResourceInputFulfillmentModeEnum getFulfillmentMode() {
    return fulfillmentMode;
  }

  public void setFulfillmentMode(@javax.annotation.Nonnull ResourceInputFulfillmentModeEnum fulfillmentMode) {
    this.fulfillmentMode = fulfillmentMode;
  }


  public ResourceCreate fulfillmentConfig(@javax.annotation.Nullable ResourceCreateFulfillmentConfig fulfillmentConfig) {
    this.fulfillmentConfig = fulfillmentConfig;
    return this;
  }

  /**
   * Get fulfillmentConfig
   * @return fulfillmentConfig
   */
  @javax.annotation.Nullable
  public ResourceCreateFulfillmentConfig getFulfillmentConfig() {
    return fulfillmentConfig;
  }

  public void setFulfillmentConfig(@javax.annotation.Nullable ResourceCreateFulfillmentConfig fulfillmentConfig) {
    this.fulfillmentConfig = fulfillmentConfig;
  }


  public ResourceCreate prices(@javax.annotation.Nonnull List<PriceInput> prices) {
    this.prices = prices;
    return this;
  }

  public ResourceCreate addPricesItem(PriceInput pricesItem) {
    if (this.prices == null) {
      this.prices = new ArrayList<>();
    }
    this.prices.add(pricesItem);
    return this;
  }

  /**
   * Get prices
   * @return prices
   */
  @javax.annotation.Nonnull
  public List<PriceInput> getPrices() {
    return prices;
  }

  public void setPrices(@javax.annotation.Nonnull List<PriceInput> prices) {
    this.prices = prices;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ResourceCreate instance itself
   */
  public ResourceCreate putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceCreate resourceCreate = (ResourceCreate) o;
    return Objects.equals(this.feeMode, resourceCreate.feeMode) &&
        Objects.equals(this.quoteCurrency, resourceCreate.quoteCurrency) &&
        Objects.equals(this.feeAllowanceCapQuoteMicros, resourceCreate.feeAllowanceCapQuoteMicros) &&
        Objects.equals(this.key, resourceCreate.key) &&
        Objects.equals(this.name, resourceCreate.name) &&
        Objects.equals(this.method, resourceCreate.method) &&
        Objects.equals(this.path, resourceCreate.path) &&
        Objects.equals(this.description, resourceCreate.description) &&
        Objects.equals(this.mimeType, resourceCreate.mimeType) &&
        Objects.equals(this.fulfillmentMode, resourceCreate.fulfillmentMode) &&
        Objects.equals(this.fulfillmentConfig, resourceCreate.fulfillmentConfig) &&
        Objects.equals(this.prices, resourceCreate.prices)&&
        Objects.equals(this.additionalProperties, resourceCreate.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feeMode, quoteCurrency, feeAllowanceCapQuoteMicros, key, name, method, path, description, mimeType, fulfillmentMode, fulfillmentConfig, prices, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceCreate {\n");
    sb.append("    feeMode: ").append(toIndentedString(feeMode)).append("\n");
    sb.append("    quoteCurrency: ").append(toIndentedString(quoteCurrency)).append("\n");
    sb.append("    feeAllowanceCapQuoteMicros: ").append(toIndentedString(feeAllowanceCapQuoteMicros)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    fulfillmentMode: ").append(toIndentedString(fulfillmentMode)).append("\n");
    sb.append("    fulfillmentConfig: ").append(toIndentedString(fulfillmentConfig)).append("\n");
    sb.append("    prices: ").append(toIndentedString(prices)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("fee_mode", "quote_currency", "fee_allowance_cap_quote_micros", "key", "name", "method", "path", "description", "mime_type", "fulfillment_mode", "fulfillment_config", "prices"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("key", "name", "method", "path", "description", "fulfillment_mode", "prices"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResourceCreate
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResourceCreate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ResourceCreate is not found in the empty JSON string", ResourceCreate.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ResourceCreate.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `fee_mode`
      if (jsonObj.get("fee_mode") != null && !jsonObj.get("fee_mode").isJsonNull()) {
        FeePolicyModeInputEnum.validateJsonElement(jsonObj.get("fee_mode"));
      }
      // validate the optional field `quote_currency`
      if (jsonObj.get("quote_currency") != null && !jsonObj.get("quote_currency").isJsonNull()) {
        FeePolicyQuoteCurrencyInputEnum.validateJsonElement(jsonObj.get("quote_currency"));
      }
      if ((jsonObj.get("fee_allowance_cap_quote_micros") != null && !jsonObj.get("fee_allowance_cap_quote_micros").isJsonNull()) && !jsonObj.get("fee_allowance_cap_quote_micros").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fee_allowance_cap_quote_micros` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fee_allowance_cap_quote_micros").toString()));
      }
      if (!jsonObj.get("key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the required field `method`
      HTTPMethodEnum.validateJsonElement(jsonObj.get("method"));
      if (!jsonObj.get("path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("path").toString()));
      }
      if (!jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("mime_type") != null && !jsonObj.get("mime_type").isJsonNull()) && !jsonObj.get("mime_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mime_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mime_type").toString()));
      }
      // validate the required field `fulfillment_mode`
      ResourceInputFulfillmentModeEnum.validateJsonElement(jsonObj.get("fulfillment_mode"));
      // validate the optional field `fulfillment_config`
      if (jsonObj.get("fulfillment_config") != null && !jsonObj.get("fulfillment_config").isJsonNull()) {
        ResourceCreateFulfillmentConfig.validateJsonElement(jsonObj.get("fulfillment_config"));
      }
      if (jsonObj.get("prices") != null) {
        if (!jsonObj.get("prices").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `prices` to be an array in the JSON string but got `%s`", jsonObj.get("prices").toString()));
        }
        JsonArray jsonArrayprices = jsonObj.getAsJsonArray("prices");
        // validate the required field `prices` (array)
        for (int i = 0; i < jsonArrayprices.size(); i++) {
          PriceInput.validateJsonElement(jsonArrayprices.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResourceCreate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResourceCreate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResourceCreate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResourceCreate.class));

       return (TypeAdapter<T>) new TypeAdapter<ResourceCreate>() {
           @Override
           public void write(JsonWriter out, ResourceCreate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ResourceCreate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ResourceCreate instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResourceCreate given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResourceCreate
   * @throws IOException if the JSON string is invalid with respect to ResourceCreate
   */
  public static ResourceCreate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResourceCreate.class);
  }

  /**
   * Convert an instance of ResourceCreate to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
