/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.x402api.client.core.JSON;

/**
 * ResourcePrice
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ResourcePrice {
  public static final String SERIALIZED_NAME_ASSET_ID = "asset_id";
  @SerializedName(SERIALIZED_NAME_ASSET_ID)
  @javax.annotation.Nonnull
  private String assetId;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  @javax.annotation.Nonnull
  private String network;

  public static final String SERIALIZED_NAME_CONTRACT_ADDRESS = "contract_address";
  @SerializedName(SERIALIZED_NAME_CONTRACT_ADDRESS)
  @javax.annotation.Nonnull
  private String contractAddress;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "display_name";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  @javax.annotation.Nonnull
  private String displayName;

  public static final String SERIALIZED_NAME_SYMBOL = "symbol";
  @SerializedName(SERIALIZED_NAME_SYMBOL)
  @javax.annotation.Nonnull
  private String symbol;

  public static final String SERIALIZED_NAME_DECIMALS = "decimals";
  @SerializedName(SERIALIZED_NAME_DECIMALS)
  @javax.annotation.Nonnull
  private Integer decimals;

  public static final String SERIALIZED_NAME_WALLET_ID = "wallet_id";
  @SerializedName(SERIALIZED_NAME_WALLET_ID)
  @javax.annotation.Nonnull
  private UUID walletId;

  public static final String SERIALIZED_NAME_WALLET_VERSION_ID = "wallet_version_id";
  @SerializedName(SERIALIZED_NAME_WALLET_VERSION_ID)
  @javax.annotation.Nonnull
  private UUID walletVersionId;

  public static final String SERIALIZED_NAME_RECIPIENT = "recipient";
  @SerializedName(SERIALIZED_NAME_RECIPIENT)
  @javax.annotation.Nonnull
  private String recipient;

  public static final String SERIALIZED_NAME_AMOUNT_ATOMIC = "amount_atomic";
  @SerializedName(SERIALIZED_NAME_AMOUNT_ATOMIC)
  @javax.annotation.Nonnull
  private String amountAtomic;

  public static final String SERIALIZED_NAME_LISTED_AMOUNT_ATOMIC = "listed_amount_atomic";
  @SerializedName(SERIALIZED_NAME_LISTED_AMOUNT_ATOMIC)
  @javax.annotation.Nonnull
  private String listedAmountAtomic;

  public static final String SERIALIZED_NAME_MAX_TIMEOUT_SECONDS = "max_timeout_seconds";
  @SerializedName(SERIALIZED_NAME_MAX_TIMEOUT_SECONDS)
  @javax.annotation.Nonnull
  private Integer maxTimeoutSeconds;

  public ResourcePrice() {
  }

  public ResourcePrice(
     String assetId,
     String network,
     String contractAddress,
     String displayName,
     String symbol,
     Integer decimals,
     UUID walletId,
     UUID walletVersionId,
     String recipient,
     String amountAtomic,
     String listedAmountAtomic,
     Integer maxTimeoutSeconds
  ) {
    this();
    this.assetId = assetId;
    this.network = network;
    this.contractAddress = contractAddress;
    this.displayName = displayName;
    this.symbol = symbol;
    this.decimals = decimals;
    this.walletId = walletId;
    this.walletVersionId = walletVersionId;
    this.recipient = recipient;
    this.amountAtomic = amountAtomic;
    this.listedAmountAtomic = listedAmountAtomic;
    this.maxTimeoutSeconds = maxTimeoutSeconds;
  }

  /**
   * Get assetId
   * @return assetId
   */
  @javax.annotation.Nonnull
  public String getAssetId() {
    return assetId;
  }



  /**
   * Get network
   * @return network
   */
  @javax.annotation.Nonnull
  public String getNetwork() {
    return network;
  }



  /**
   * Get contractAddress
   * @return contractAddress
   */
  @javax.annotation.Nonnull
  public String getContractAddress() {
    return contractAddress;
  }



  /**
   * Get displayName
   * @return displayName
   */
  @javax.annotation.Nonnull
  public String getDisplayName() {
    return displayName;
  }



  /**
   * Get symbol
   * @return symbol
   */
  @javax.annotation.Nonnull
  public String getSymbol() {
    return symbol;
  }



  /**
   * Get decimals
   * @return decimals
   */
  @javax.annotation.Nonnull
  public Integer getDecimals() {
    return decimals;
  }



  /**
   * Get walletId
   * @return walletId
   */
  @javax.annotation.Nonnull
  public UUID getWalletId() {
    return walletId;
  }



  /**
   * Get walletVersionId
   * @return walletVersionId
   */
  @javax.annotation.Nonnull
  public UUID getWalletVersionId() {
    return walletVersionId;
  }



  /**
   * Get recipient
   * @return recipient
   */
  @javax.annotation.Nonnull
  public String getRecipient() {
    return recipient;
  }



  /**
   * Get amountAtomic
   * @return amountAtomic
   */
  @javax.annotation.Nonnull
  public String getAmountAtomic() {
    return amountAtomic;
  }



  /**
   * Get listedAmountAtomic
   * @return listedAmountAtomic
   */
  @javax.annotation.Nonnull
  public String getListedAmountAtomic() {
    return listedAmountAtomic;
  }



  /**
   * Get maxTimeoutSeconds
   * @return maxTimeoutSeconds
   */
  @javax.annotation.Nonnull
  public Integer getMaxTimeoutSeconds() {
    return maxTimeoutSeconds;
  }


  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ResourcePrice instance itself
   */
  public ResourcePrice putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourcePrice resourcePrice = (ResourcePrice) o;
    return Objects.equals(this.assetId, resourcePrice.assetId) &&
        Objects.equals(this.network, resourcePrice.network) &&
        Objects.equals(this.contractAddress, resourcePrice.contractAddress) &&
        Objects.equals(this.displayName, resourcePrice.displayName) &&
        Objects.equals(this.symbol, resourcePrice.symbol) &&
        Objects.equals(this.decimals, resourcePrice.decimals) &&
        Objects.equals(this.walletId, resourcePrice.walletId) &&
        Objects.equals(this.walletVersionId, resourcePrice.walletVersionId) &&
        Objects.equals(this.recipient, resourcePrice.recipient) &&
        Objects.equals(this.amountAtomic, resourcePrice.amountAtomic) &&
        Objects.equals(this.listedAmountAtomic, resourcePrice.listedAmountAtomic) &&
        Objects.equals(this.maxTimeoutSeconds, resourcePrice.maxTimeoutSeconds)&&
        Objects.equals(this.additionalProperties, resourcePrice.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetId, network, contractAddress, displayName, symbol, decimals, walletId, walletVersionId, recipient, amountAtomic, listedAmountAtomic, maxTimeoutSeconds, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourcePrice {\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("    walletId: ").append(toIndentedString(walletId)).append("\n");
    sb.append("    walletVersionId: ").append(toIndentedString(walletVersionId)).append("\n");
    sb.append("    recipient: ").append(toIndentedString(recipient)).append("\n");
    sb.append("    amountAtomic: ").append(toIndentedString(amountAtomic)).append("\n");
    sb.append("    listedAmountAtomic: ").append(toIndentedString(listedAmountAtomic)).append("\n");
    sb.append("    maxTimeoutSeconds: ").append(toIndentedString(maxTimeoutSeconds)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("asset_id", "network", "contract_address", "display_name", "symbol", "decimals", "wallet_id", "wallet_version_id", "recipient", "amount_atomic", "listed_amount_atomic", "max_timeout_seconds"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("asset_id", "network", "contract_address", "display_name", "symbol", "decimals", "wallet_id", "wallet_version_id", "recipient", "amount_atomic", "listed_amount_atomic", "max_timeout_seconds"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResourcePrice
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResourcePrice.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ResourcePrice is not found in the empty JSON string", ResourcePrice.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ResourcePrice.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("asset_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `asset_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asset_id").toString()));
      }
      if (!jsonObj.get("network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network").toString()));
      }
      if (!jsonObj.get("contract_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contract_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contract_address").toString()));
      }
      if (!jsonObj.get("display_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `display_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("display_name").toString()));
      }
      if (!jsonObj.get("symbol").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbol").toString()));
      }
      if (!jsonObj.get("wallet_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `wallet_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wallet_id").toString()));
      }
      if (!jsonObj.get("wallet_version_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `wallet_version_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wallet_version_id").toString()));
      }
      if (!jsonObj.get("recipient").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recipient` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recipient").toString()));
      }
      if (!jsonObj.get("amount_atomic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `amount_atomic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount_atomic").toString()));
      }
      if (!jsonObj.get("listed_amount_atomic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `listed_amount_atomic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("listed_amount_atomic").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResourcePrice.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResourcePrice' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResourcePrice> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResourcePrice.class));

       return (TypeAdapter<T>) new TypeAdapter<ResourcePrice>() {
           @Override
           public void write(JsonWriter out, ResourcePrice value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ResourcePrice read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ResourcePrice instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResourcePrice given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResourcePrice
   * @throws IOException if the JSON string is invalid with respect to ResourcePrice
   */
  public static ResourcePrice fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResourcePrice.class);
  }

  /**
   * Convert an instance of ResourcePrice to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
