/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * * &#x60;proxy&#x60; - Reverse proxy * &#x60;webhook&#x60; - Signed webhook * &#x60;static&#x60; - Static response * &#x60;entitlement&#x60; - Paid entitlement
 */
@JsonAdapter(ResourceVersionFulfillmentModeEnum.Adapter.class)
public enum ResourceVersionFulfillmentModeEnum {

  PROXY("proxy"),

  WEBHOOK("webhook"),

  STATIC("static"),

  ENTITLEMENT("entitlement"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  ResourceVersionFulfillmentModeEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ResourceVersionFulfillmentModeEnum fromValue(String value) {
    for (ResourceVersionFulfillmentModeEnum b : ResourceVersionFulfillmentModeEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<ResourceVersionFulfillmentModeEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final ResourceVersionFulfillmentModeEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ResourceVersionFulfillmentModeEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ResourceVersionFulfillmentModeEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ResourceVersionFulfillmentModeEnum.fromValue(value);
  }
}
