/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.x402api.client.model.SettlementChainObservationStateEnum;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.x402api.client.core.JSON;

/**
 * SettlementChainObservation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SettlementChainObservation {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private UUID id;

  public static final String SERIALIZED_NAME_SETTLEMENT_JOB_ID = "settlement_job_id";
  @SerializedName(SERIALIZED_NAME_SETTLEMENT_JOB_ID)
  @javax.annotation.Nonnull
  private UUID settlementJobId;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  @javax.annotation.Nonnull
  private String network;

  public static final String SERIALIZED_NAME_TRANSACTION_HASH = "transaction_hash";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_HASH)
  @javax.annotation.Nonnull
  private String transactionHash;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nonnull
  private SettlementChainObservationStateEnum state;

  public static final String SERIALIZED_NAME_OBSERVATION_DIGEST = "observation_digest";
  @SerializedName(SERIALIZED_NAME_OBSERVATION_DIGEST)
  @javax.annotation.Nonnull
  private String observationDigest;

  public static final String SERIALIZED_NAME_LOG_INDEX = "log_index";
  @SerializedName(SERIALIZED_NAME_LOG_INDEX)
  @javax.annotation.Nullable
  private Integer logIndex;

  public static final String SERIALIZED_NAME_BLOCK_NUMBER = "block_number";
  @SerializedName(SERIALIZED_NAME_BLOCK_NUMBER)
  @javax.annotation.Nullable
  private String blockNumber;

  public static final String SERIALIZED_NAME_BLOCK_HASH = "block_hash";
  @SerializedName(SERIALIZED_NAME_BLOCK_HASH)
  @javax.annotation.Nonnull
  private String blockHash;

  public static final String SERIALIZED_NAME_ASSET_CONTRACT = "asset_contract";
  @SerializedName(SERIALIZED_NAME_ASSET_CONTRACT)
  @javax.annotation.Nonnull
  private String assetContract;

  public static final String SERIALIZED_NAME_PAYER = "payer";
  @SerializedName(SERIALIZED_NAME_PAYER)
  @javax.annotation.Nonnull
  private String payer;

  public static final String SERIALIZED_NAME_RECIPIENT = "recipient";
  @SerializedName(SERIALIZED_NAME_RECIPIENT)
  @javax.annotation.Nonnull
  private String recipient;

  public static final String SERIALIZED_NAME_AMOUNT_ATOMIC = "amount_atomic";
  @SerializedName(SERIALIZED_NAME_AMOUNT_ATOMIC)
  @javax.annotation.Nullable
  private String amountAtomic;

  public static final String SERIALIZED_NAME_EXECUTION_SUCCESS = "execution_success";
  @SerializedName(SERIALIZED_NAME_EXECUTION_SUCCESS)
  @javax.annotation.Nullable
  private Boolean executionSuccess;

  public static final String SERIALIZED_NAME_OBSERVED_AT = "observed_at";
  @SerializedName(SERIALIZED_NAME_OBSERVED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime observedAt;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public SettlementChainObservation() {
  }

  public SettlementChainObservation(
     UUID id,
     UUID settlementJobId,
     String network,
     String transactionHash,
     SettlementChainObservationStateEnum state,
     String observationDigest,
     Integer logIndex,
     String blockNumber,
     String blockHash,
     String assetContract,
     String payer,
     String recipient,
     String amountAtomic,
     Boolean executionSuccess,
     OffsetDateTime observedAt,
     OffsetDateTime createdAt
  ) {
    this();
    this.id = id;
    this.settlementJobId = settlementJobId;
    this.network = network;
    this.transactionHash = transactionHash;
    this.state = state;
    this.observationDigest = observationDigest;
    this.logIndex = logIndex;
    this.blockNumber = blockNumber;
    this.blockHash = blockHash;
    this.assetContract = assetContract;
    this.payer = payer;
    this.recipient = recipient;
    this.amountAtomic = amountAtomic;
    this.executionSuccess = executionSuccess;
    this.observedAt = observedAt;
    this.createdAt = createdAt;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public UUID getId() {
    return id;
  }



  /**
   * Get settlementJobId
   * @return settlementJobId
   */
  @javax.annotation.Nonnull
  public UUID getSettlementJobId() {
    return settlementJobId;
  }



  /**
   * Get network
   * @return network
   */
  @javax.annotation.Nonnull
  public String getNetwork() {
    return network;
  }



  /**
   * Get transactionHash
   * @return transactionHash
   */
  @javax.annotation.Nonnull
  public String getTransactionHash() {
    return transactionHash;
  }



  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nonnull
  public SettlementChainObservationStateEnum getState() {
    return state;
  }



  /**
   * Get observationDigest
   * @return observationDigest
   */
  @javax.annotation.Nonnull
  public String getObservationDigest() {
    return observationDigest;
  }



  /**
   * Get logIndex
   * @return logIndex
   */
  @javax.annotation.Nullable
  public Integer getLogIndex() {
    return logIndex;
  }



  /**
   * Get blockNumber
   * @return blockNumber
   */
  @javax.annotation.Nullable
  public String getBlockNumber() {
    return blockNumber;
  }



  /**
   * Get blockHash
   * @return blockHash
   */
  @javax.annotation.Nonnull
  public String getBlockHash() {
    return blockHash;
  }



  /**
   * Get assetContract
   * @return assetContract
   */
  @javax.annotation.Nonnull
  public String getAssetContract() {
    return assetContract;
  }



  /**
   * Get payer
   * @return payer
   */
  @javax.annotation.Nonnull
  public String getPayer() {
    return payer;
  }



  /**
   * Get recipient
   * @return recipient
   */
  @javax.annotation.Nonnull
  public String getRecipient() {
    return recipient;
  }



  /**
   * Get amountAtomic
   * @return amountAtomic
   */
  @javax.annotation.Nullable
  public String getAmountAtomic() {
    return amountAtomic;
  }



  /**
   * Get executionSuccess
   * @return executionSuccess
   */
  @javax.annotation.Nullable
  public Boolean getExecutionSuccess() {
    return executionSuccess;
  }



  /**
   * Get observedAt
   * @return observedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getObservedAt() {
    return observedAt;
  }



  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SettlementChainObservation instance itself
   */
  public SettlementChainObservation putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SettlementChainObservation settlementChainObservation = (SettlementChainObservation) o;
    return Objects.equals(this.id, settlementChainObservation.id) &&
        Objects.equals(this.settlementJobId, settlementChainObservation.settlementJobId) &&
        Objects.equals(this.network, settlementChainObservation.network) &&
        Objects.equals(this.transactionHash, settlementChainObservation.transactionHash) &&
        Objects.equals(this.state, settlementChainObservation.state) &&
        Objects.equals(this.observationDigest, settlementChainObservation.observationDigest) &&
        Objects.equals(this.logIndex, settlementChainObservation.logIndex) &&
        Objects.equals(this.blockNumber, settlementChainObservation.blockNumber) &&
        Objects.equals(this.blockHash, settlementChainObservation.blockHash) &&
        Objects.equals(this.assetContract, settlementChainObservation.assetContract) &&
        Objects.equals(this.payer, settlementChainObservation.payer) &&
        Objects.equals(this.recipient, settlementChainObservation.recipient) &&
        Objects.equals(this.amountAtomic, settlementChainObservation.amountAtomic) &&
        Objects.equals(this.executionSuccess, settlementChainObservation.executionSuccess) &&
        Objects.equals(this.observedAt, settlementChainObservation.observedAt) &&
        Objects.equals(this.createdAt, settlementChainObservation.createdAt)&&
        Objects.equals(this.additionalProperties, settlementChainObservation.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, settlementJobId, network, transactionHash, state, observationDigest, logIndex, blockNumber, blockHash, assetContract, payer, recipient, amountAtomic, executionSuccess, observedAt, createdAt, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettlementChainObservation {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    settlementJobId: ").append(toIndentedString(settlementJobId)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    observationDigest: ").append(toIndentedString(observationDigest)).append("\n");
    sb.append("    logIndex: ").append(toIndentedString(logIndex)).append("\n");
    sb.append("    blockNumber: ").append(toIndentedString(blockNumber)).append("\n");
    sb.append("    blockHash: ").append(toIndentedString(blockHash)).append("\n");
    sb.append("    assetContract: ").append(toIndentedString(assetContract)).append("\n");
    sb.append("    payer: ").append(toIndentedString(payer)).append("\n");
    sb.append("    recipient: ").append(toIndentedString(recipient)).append("\n");
    sb.append("    amountAtomic: ").append(toIndentedString(amountAtomic)).append("\n");
    sb.append("    executionSuccess: ").append(toIndentedString(executionSuccess)).append("\n");
    sb.append("    observedAt: ").append(toIndentedString(observedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "settlement_job_id", "network", "transaction_hash", "state", "observation_digest", "log_index", "block_number", "block_hash", "asset_contract", "payer", "recipient", "amount_atomic", "execution_success", "observed_at", "created_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "settlement_job_id", "network", "transaction_hash", "state", "observation_digest", "log_index", "block_number", "block_hash", "asset_contract", "payer", "recipient", "amount_atomic", "execution_success", "observed_at", "created_at"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SettlementChainObservation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SettlementChainObservation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SettlementChainObservation is not found in the empty JSON string", SettlementChainObservation.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SettlementChainObservation.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("settlement_job_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `settlement_job_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("settlement_job_id").toString()));
      }
      if (!jsonObj.get("network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network").toString()));
      }
      if (!jsonObj.get("transaction_hash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transaction_hash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transaction_hash").toString()));
      }
      // validate the required field `state`
      SettlementChainObservationStateEnum.validateJsonElement(jsonObj.get("state"));
      if (!jsonObj.get("observation_digest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `observation_digest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("observation_digest").toString()));
      }
      if ((jsonObj.get("block_number") != null && !jsonObj.get("block_number").isJsonNull()) && !jsonObj.get("block_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `block_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("block_number").toString()));
      }
      if (!jsonObj.get("block_hash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `block_hash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("block_hash").toString()));
      }
      if (!jsonObj.get("asset_contract").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `asset_contract` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asset_contract").toString()));
      }
      if (!jsonObj.get("payer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payer").toString()));
      }
      if (!jsonObj.get("recipient").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recipient` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recipient").toString()));
      }
      if ((jsonObj.get("amount_atomic") != null && !jsonObj.get("amount_atomic").isJsonNull()) && !jsonObj.get("amount_atomic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `amount_atomic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount_atomic").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SettlementChainObservation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SettlementChainObservation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SettlementChainObservation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SettlementChainObservation.class));

       return (TypeAdapter<T>) new TypeAdapter<SettlementChainObservation>() {
           @Override
           public void write(JsonWriter out, SettlementChainObservation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SettlementChainObservation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             SettlementChainObservation instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SettlementChainObservation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SettlementChainObservation
   * @throws IOException if the JSON string is invalid with respect to SettlementChainObservation
   */
  public static SettlementChainObservation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SettlementChainObservation.class);
  }

  /**
   * Convert an instance of SettlementChainObservation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
