/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * * &#x60;created&#x60; - Created * &#x60;verifying&#x60; - Verifying * &#x60;verified&#x60; - Verified * &#x60;reserved&#x60; - Reserved * &#x60;broadcasting&#x60; - Broadcasting * &#x60;broadcast_unknown&#x60; - Broadcast unknown * &#x60;broadcast&#x60; - Broadcast * &#x60;confirming&#x60; - Confirming * &#x60;confirmed&#x60; - Confirmed * &#x60;finalized&#x60; - Finalized * &#x60;rejected&#x60; - Rejected * &#x60;failed&#x60; - Failed * &#x60;expired&#x60; - Expired * &#x60;reverted&#x60; - Reverted * &#x60;reorged&#x60; - Reorged * &#x60;late_confirmed&#x60; - Late confirmed * &#x60;manual_review&#x60; - Manual review
 */
@JsonAdapter(SettlementJobStateEnum.Adapter.class)
public enum SettlementJobStateEnum {

  CREATED("created"),

  VERIFYING("verifying"),

  VERIFIED("verified"),

  RESERVED("reserved"),

  BROADCASTING("broadcasting"),

  BROADCAST_UNKNOWN("broadcast_unknown"),

  BROADCAST("broadcast"),

  CONFIRMING("confirming"),

  CONFIRMED("confirmed"),

  FINALIZED("finalized"),

  REJECTED("rejected"),

  FAILED("failed"),

  EXPIRED("expired"),

  REVERTED("reverted"),

  REORGED("reorged"),

  LATE_CONFIRMED("late_confirmed"),

  MANUAL_REVIEW("manual_review"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  SettlementJobStateEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SettlementJobStateEnum fromValue(String value) {
    for (SettlementJobStateEnum b : SettlementJobStateEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<SettlementJobStateEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final SettlementJobStateEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SettlementJobStateEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SettlementJobStateEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    SettlementJobStateEnum.fromValue(value);
  }
}
