/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * * &#x60;not_enforced&#x60; - not_enforced * &#x60;allowed&#x60; - allowed * &#x60;not_allowed&#x60; - not_allowed * &#x60;unavailable&#x60; - unavailable
 */
@JsonAdapter(TenantPaymentScreeningSubjectProjectionStatusEnum.Adapter.class)
public enum TenantPaymentScreeningSubjectProjectionStatusEnum {

  NOT_ENFORCED("not_enforced"),

  ALLOWED("allowed"),

  NOT_ALLOWED("not_allowed"),

  UNAVAILABLE("unavailable"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  TenantPaymentScreeningSubjectProjectionStatusEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TenantPaymentScreeningSubjectProjectionStatusEnum fromValue(String value) {
    for (TenantPaymentScreeningSubjectProjectionStatusEnum b : TenantPaymentScreeningSubjectProjectionStatusEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<TenantPaymentScreeningSubjectProjectionStatusEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final TenantPaymentScreeningSubjectProjectionStatusEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TenantPaymentScreeningSubjectProjectionStatusEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TenantPaymentScreeningSubjectProjectionStatusEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TenantPaymentScreeningSubjectProjectionStatusEnum.fromValue(value);
  }
}
