/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.api;

import com.x402api.client.core.ApiCallback;
import com.x402api.client.core.ApiClient;
import com.x402api.client.core.ApiException;
import com.x402api.client.core.ApiResponse;
import com.x402api.client.core.Configuration;
import com.x402api.client.core.Pair;
import com.x402api.client.core.ProgressRequestBody;
import com.x402api.client.core.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.x402api.client.model.ApiErrorEnvelope;
import com.x402api.client.model.PaymentReadiness;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AssetsAndPaymentControlsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AssetsAndPaymentControlsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AssetsAndPaymentControlsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for paymentReadinessRetrieve
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for retrieve payment readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call paymentReadinessRetrieveCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/payment-readiness";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call paymentReadinessRetrieveValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return paymentReadinessRetrieveCall(_callback);

    }

    /**
     * Retrieve payment readiness
     * Return the tenant&#39;s current external-wallet payment-readiness projection.
     * @return PaymentReadiness
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for retrieve payment readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public PaymentReadiness paymentReadinessRetrieve() throws ApiException {
        ApiResponse<PaymentReadiness> localVarResp = paymentReadinessRetrieveWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Retrieve payment readiness
     * Return the tenant&#39;s current external-wallet payment-readiness projection.
     * @return ApiResponse&lt;PaymentReadiness&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for retrieve payment readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<PaymentReadiness> paymentReadinessRetrieveWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = paymentReadinessRetrieveValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<PaymentReadiness>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve payment readiness (asynchronously)
     * Return the tenant&#39;s current external-wallet payment-readiness projection.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for retrieve payment readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call paymentReadinessRetrieveAsync(final ApiCallback<PaymentReadiness> _callback) throws ApiException {

        okhttp3.Call localVarCall = paymentReadinessRetrieveValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<PaymentReadiness>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
