/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.api;

import com.x402api.client.core.ApiCallback;
import com.x402api.client.core.ApiClient;
import com.x402api.client.core.ApiException;
import com.x402api.client.core.ApiResponse;
import com.x402api.client.core.Configuration;
import com.x402api.client.core.Pair;
import com.x402api.client.core.ProgressRequestBody;
import com.x402api.client.core.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.x402api.client.model.ApiErrorEnvelope;
import com.x402api.client.model.ExternalAddressControlCapabilities;
import com.x402api.client.model.ExternalAddressControlChallenge;
import com.x402api.client.model.ExternalAddressControlChallengeCreate;
import com.x402api.client.model.ExternalReceivingAddress;
import com.x402api.client.model.ExternalReceivingAddressCreate;
import com.x402api.client.model.ExternalReceivingAddressRotation;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ReceivingAddressesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ReceivingAddressesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ReceivingAddressesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for receivingAddressesActivate
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for activate a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesActivateCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses/{readiness_id}/activate"
            .replace("{" + "readiness_id" + "}", localVarApiClient.escapeString(readinessId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call receivingAddressesActivateValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling receivingAddressesActivate(Async)");
        }

        // verify the required parameter 'readinessId' is set
        if (readinessId == null) {
            throw new ApiException("Missing the required parameter 'readinessId' when calling receivingAddressesActivate(Async)");
        }

        return receivingAddressesActivateCall(idempotencyKey, readinessId, _callback);

    }

    /**
     * Activate a receiving address
     * Activate a ready external receiving-address registration idempotently.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @return ExternalReceivingAddress
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for activate a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ExternalReceivingAddress receivingAddressesActivate(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId) throws ApiException {
        ApiResponse<ExternalReceivingAddress> localVarResp = receivingAddressesActivateWithHttpInfo(idempotencyKey, readinessId);
        return localVarResp.getData();
    }

    /**
     * Activate a receiving address
     * Activate a ready external receiving-address registration idempotently.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @return ApiResponse&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for activate a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<ExternalReceivingAddress> receivingAddressesActivateWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId) throws ApiException {
        okhttp3.Call localVarCall = receivingAddressesActivateValidateBeforeCall(idempotencyKey, readinessId, null);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Activate a receiving address (asynchronously)
     * Activate a ready external receiving-address registration idempotently.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for activate a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesActivateAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback<ExternalReceivingAddress> _callback) throws ApiException {

        okhttp3.Call localVarCall = receivingAddressesActivateValidateBeforeCall(idempotencyKey, readinessId, _callback);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for receivingAddressesCreateControlChallenge
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param externalAddressControlChallengeCreate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for create a receiving-address control challenge. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesCreateControlChallengeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = externalAddressControlChallengeCreate;

        // create path and map variables
        String localVarPath = "/v1/receiving-address-control-challenges";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call receivingAddressesCreateControlChallengeValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling receivingAddressesCreateControlChallenge(Async)");
        }

        // verify the required parameter 'externalAddressControlChallengeCreate' is set
        if (externalAddressControlChallengeCreate == null) {
            throw new ApiException("Missing the required parameter 'externalAddressControlChallengeCreate' when calling receivingAddressesCreateControlChallenge(Async)");
        }

        return receivingAddressesCreateControlChallengeCall(idempotencyKey, externalAddressControlChallengeCreate, _callback);

    }

    /**
     * Create a receiving-address control challenge
     * Create an idempotent proof-of-control challenge for an external receiving address.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param externalAddressControlChallengeCreate  (required)
     * @return ExternalAddressControlChallenge
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for create a receiving-address control challenge. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ExternalAddressControlChallenge receivingAddressesCreateControlChallenge(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate) throws ApiException {
        ApiResponse<ExternalAddressControlChallenge> localVarResp = receivingAddressesCreateControlChallengeWithHttpInfo(idempotencyKey, externalAddressControlChallengeCreate);
        return localVarResp.getData();
    }

    /**
     * Create a receiving-address control challenge
     * Create an idempotent proof-of-control challenge for an external receiving address.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param externalAddressControlChallengeCreate  (required)
     * @return ApiResponse&lt;ExternalAddressControlChallenge&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for create a receiving-address control challenge. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<ExternalAddressControlChallenge> receivingAddressesCreateControlChallengeWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate) throws ApiException {
        okhttp3.Call localVarCall = receivingAddressesCreateControlChallengeValidateBeforeCall(idempotencyKey, externalAddressControlChallengeCreate, null);
        Type localVarReturnType = new TypeToken<ExternalAddressControlChallenge>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a receiving-address control challenge (asynchronously)
     * Create an idempotent proof-of-control challenge for an external receiving address.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param externalAddressControlChallengeCreate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for create a receiving-address control challenge. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesCreateControlChallengeAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate, final ApiCallback<ExternalAddressControlChallenge> _callback) throws ApiException {

        okhttp3.Call localVarCall = receivingAddressesCreateControlChallengeValidateBeforeCall(idempotencyKey, externalAddressControlChallengeCreate, _callback);
        Type localVarReturnType = new TypeToken<ExternalAddressControlChallenge>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for receivingAddressesGetControlCapabilities
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for get receiving-address control capabilities. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesGetControlCapabilitiesCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/receiving-address-control-capabilities";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call receivingAddressesGetControlCapabilitiesValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return receivingAddressesGetControlCapabilitiesCall(_callback);

    }

    /**
     * Get receiving-address control capabilities
     * Return the supported proof and control capabilities for external receiving addresses.
     * @return ExternalAddressControlCapabilities
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for get receiving-address control capabilities. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ExternalAddressControlCapabilities receivingAddressesGetControlCapabilities() throws ApiException {
        ApiResponse<ExternalAddressControlCapabilities> localVarResp = receivingAddressesGetControlCapabilitiesWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get receiving-address control capabilities
     * Return the supported proof and control capabilities for external receiving addresses.
     * @return ApiResponse&lt;ExternalAddressControlCapabilities&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for get receiving-address control capabilities. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<ExternalAddressControlCapabilities> receivingAddressesGetControlCapabilitiesWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = receivingAddressesGetControlCapabilitiesValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ExternalAddressControlCapabilities>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get receiving-address control capabilities (asynchronously)
     * Return the supported proof and control capabilities for external receiving addresses.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for get receiving-address control capabilities. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesGetControlCapabilitiesAsync(final ApiCallback<ExternalAddressControlCapabilities> _callback) throws ApiException {

        okhttp3.Call localVarCall = receivingAddressesGetControlCapabilitiesValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ExternalAddressControlCapabilities>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for receivingAddressesList
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for list receiving addresses. </td><td>  * X-Request-ID -  <br>  * Link -  <br>  * X-X402API-Next-Cursor -  <br>  * X-X402API-Result-Truncated -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesListCall(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call receivingAddressesListValidateBeforeCall(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize, final ApiCallback _callback) throws ApiException {
        return receivingAddressesListCall(cursor, pageSize, _callback);

    }

    /**
     * List receiving addresses
     * List tenant receiving-address registrations using opaque cursor pagination.
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @return List&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for list receiving addresses. </td><td>  * X-Request-ID -  <br>  * Link -  <br>  * X-X402API-Next-Cursor -  <br>  * X-X402API-Result-Truncated -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public List<ExternalReceivingAddress> receivingAddressesList(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize) throws ApiException {
        ApiResponse<List<ExternalReceivingAddress>> localVarResp = receivingAddressesListWithHttpInfo(cursor, pageSize);
        return localVarResp.getData();
    }

    /**
     * List receiving addresses
     * List tenant receiving-address registrations using opaque cursor pagination.
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @return ApiResponse&lt;List&lt;ExternalReceivingAddress&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for list receiving addresses. </td><td>  * X-Request-ID -  <br>  * Link -  <br>  * X-X402API-Next-Cursor -  <br>  * X-X402API-Result-Truncated -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<List<ExternalReceivingAddress>> receivingAddressesListWithHttpInfo(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize) throws ApiException {
        okhttp3.Call localVarCall = receivingAddressesListValidateBeforeCall(cursor, pageSize, null);
        Type localVarReturnType = new TypeToken<List<ExternalReceivingAddress>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List receiving addresses (asynchronously)
     * List tenant receiving-address registrations using opaque cursor pagination.
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for list receiving addresses. </td><td>  * X-Request-ID -  <br>  * Link -  <br>  * X-X402API-Next-Cursor -  <br>  * X-X402API-Result-Truncated -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesListAsync(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize, final ApiCallback<List<ExternalReceivingAddress>> _callback) throws ApiException {

        okhttp3.Call localVarCall = receivingAddressesListValidateBeforeCall(cursor, pageSize, _callback);
        Type localVarReturnType = new TypeToken<List<ExternalReceivingAddress>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for receivingAddressesRefreshReadiness
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for refresh receiving-address readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 201 </td><td> Successful response for refresh receiving-address readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesRefreshReadinessCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses/{readiness_id}/readiness-refreshes"
            .replace("{" + "readiness_id" + "}", localVarApiClient.escapeString(readinessId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call receivingAddressesRefreshReadinessValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling receivingAddressesRefreshReadiness(Async)");
        }

        // verify the required parameter 'readinessId' is set
        if (readinessId == null) {
            throw new ApiException("Missing the required parameter 'readinessId' when calling receivingAddressesRefreshReadiness(Async)");
        }

        return receivingAddressesRefreshReadinessCall(idempotencyKey, readinessId, _callback);

    }

    /**
     * Refresh receiving-address readiness
     * Request an idempotent refresh of external receiving-address readiness evidence.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @return ExternalReceivingAddress
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for refresh receiving-address readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 201 </td><td> Successful response for refresh receiving-address readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ExternalReceivingAddress receivingAddressesRefreshReadiness(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId) throws ApiException {
        ApiResponse<ExternalReceivingAddress> localVarResp = receivingAddressesRefreshReadinessWithHttpInfo(idempotencyKey, readinessId);
        return localVarResp.getData();
    }

    /**
     * Refresh receiving-address readiness
     * Request an idempotent refresh of external receiving-address readiness evidence.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @return ApiResponse&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for refresh receiving-address readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 201 </td><td> Successful response for refresh receiving-address readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<ExternalReceivingAddress> receivingAddressesRefreshReadinessWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId) throws ApiException {
        okhttp3.Call localVarCall = receivingAddressesRefreshReadinessValidateBeforeCall(idempotencyKey, readinessId, null);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Refresh receiving-address readiness (asynchronously)
     * Request an idempotent refresh of external receiving-address readiness evidence.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for refresh receiving-address readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 201 </td><td> Successful response for refresh receiving-address readiness. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesRefreshReadinessAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback<ExternalReceivingAddress> _callback) throws ApiException {

        okhttp3.Call localVarCall = receivingAddressesRefreshReadinessValidateBeforeCall(idempotencyKey, readinessId, _callback);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for receivingAddressesRegister
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param externalReceivingAddressCreate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for register a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesRegisterCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalReceivingAddressCreate externalReceivingAddressCreate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = externalReceivingAddressCreate;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call receivingAddressesRegisterValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalReceivingAddressCreate externalReceivingAddressCreate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling receivingAddressesRegister(Async)");
        }

        // verify the required parameter 'externalReceivingAddressCreate' is set
        if (externalReceivingAddressCreate == null) {
            throw new ApiException("Missing the required parameter 'externalReceivingAddressCreate' when calling receivingAddressesRegister(Async)");
        }

        return receivingAddressesRegisterCall(idempotencyKey, externalReceivingAddressCreate, _callback);

    }

    /**
     * Register a receiving address
     * Register a proven external receiving address without transferring wallet custody.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param externalReceivingAddressCreate  (required)
     * @return ExternalReceivingAddress
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for register a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ExternalReceivingAddress receivingAddressesRegister(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalReceivingAddressCreate externalReceivingAddressCreate) throws ApiException {
        ApiResponse<ExternalReceivingAddress> localVarResp = receivingAddressesRegisterWithHttpInfo(idempotencyKey, externalReceivingAddressCreate);
        return localVarResp.getData();
    }

    /**
     * Register a receiving address
     * Register a proven external receiving address without transferring wallet custody.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param externalReceivingAddressCreate  (required)
     * @return ApiResponse&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for register a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<ExternalReceivingAddress> receivingAddressesRegisterWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalReceivingAddressCreate externalReceivingAddressCreate) throws ApiException {
        okhttp3.Call localVarCall = receivingAddressesRegisterValidateBeforeCall(idempotencyKey, externalReceivingAddressCreate, null);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Register a receiving address (asynchronously)
     * Register a proven external receiving address without transferring wallet custody.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param externalReceivingAddressCreate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for register a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesRegisterAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalReceivingAddressCreate externalReceivingAddressCreate, final ApiCallback<ExternalReceivingAddress> _callback) throws ApiException {

        okhttp3.Call localVarCall = receivingAddressesRegisterValidateBeforeCall(idempotencyKey, externalReceivingAddressCreate, _callback);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for receivingAddressesRotate
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @param externalReceivingAddressRotation  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for rotate a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesRotateCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, @javax.annotation.Nonnull ExternalReceivingAddressRotation externalReceivingAddressRotation, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = externalReceivingAddressRotation;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses/{readiness_id}/rotations"
            .replace("{" + "readiness_id" + "}", localVarApiClient.escapeString(readinessId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call receivingAddressesRotateValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, @javax.annotation.Nonnull ExternalReceivingAddressRotation externalReceivingAddressRotation, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling receivingAddressesRotate(Async)");
        }

        // verify the required parameter 'readinessId' is set
        if (readinessId == null) {
            throw new ApiException("Missing the required parameter 'readinessId' when calling receivingAddressesRotate(Async)");
        }

        // verify the required parameter 'externalReceivingAddressRotation' is set
        if (externalReceivingAddressRotation == null) {
            throw new ApiException("Missing the required parameter 'externalReceivingAddressRotation' when calling receivingAddressesRotate(Async)");
        }

        return receivingAddressesRotateCall(idempotencyKey, readinessId, externalReceivingAddressRotation, _callback);

    }

    /**
     * Rotate a receiving address
     * Create an idempotent receiving-address rotation from a proven replacement.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @param externalReceivingAddressRotation  (required)
     * @return ExternalReceivingAddress
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for rotate a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ExternalReceivingAddress receivingAddressesRotate(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, @javax.annotation.Nonnull ExternalReceivingAddressRotation externalReceivingAddressRotation) throws ApiException {
        ApiResponse<ExternalReceivingAddress> localVarResp = receivingAddressesRotateWithHttpInfo(idempotencyKey, readinessId, externalReceivingAddressRotation);
        return localVarResp.getData();
    }

    /**
     * Rotate a receiving address
     * Create an idempotent receiving-address rotation from a proven replacement.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @param externalReceivingAddressRotation  (required)
     * @return ApiResponse&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for rotate a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<ExternalReceivingAddress> receivingAddressesRotateWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, @javax.annotation.Nonnull ExternalReceivingAddressRotation externalReceivingAddressRotation) throws ApiException {
        okhttp3.Call localVarCall = receivingAddressesRotateValidateBeforeCall(idempotencyKey, readinessId, externalReceivingAddressRotation, null);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Rotate a receiving address (asynchronously)
     * Create an idempotent receiving-address rotation from a proven replacement.
     * @param idempotencyKey Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome. (required)
     * @param readinessId  (required)
     * @param externalReceivingAddressRotation  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful response for rotate a receiving address. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesRotateAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, @javax.annotation.Nonnull ExternalReceivingAddressRotation externalReceivingAddressRotation, final ApiCallback<ExternalReceivingAddress> _callback) throws ApiException {

        okhttp3.Call localVarCall = receivingAddressesRotateValidateBeforeCall(idempotencyKey, readinessId, externalReceivingAddressRotation, _callback);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
