/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.api;

import com.x402api.client.core.ApiCallback;
import com.x402api.client.core.ApiClient;
import com.x402api.client.core.ApiException;
import com.x402api.client.core.ApiResponse;
import com.x402api.client.core.Configuration;
import com.x402api.client.core.Pair;
import com.x402api.client.core.ProgressRequestBody;
import com.x402api.client.core.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.x402api.client.model.ExternalAddressControlCapabilities;
import com.x402api.client.model.ExternalAddressControlChallenge;
import com.x402api.client.model.ExternalAddressControlChallengeCreate;
import com.x402api.client.model.ExternalReceivingAddress;
import com.x402api.client.model.ExternalReceivingAddressCreate;
import com.x402api.client.model.ExternalReceivingAddressRotation;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ReceivingAddressesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ReceivingAddressesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ReceivingAddressesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for v1ReceivingAddressControlCapabilitiesRetrieve
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressControlCapabilitiesRetrieveCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/receiving-address-control-capabilities";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ReceivingAddressControlCapabilitiesRetrieveValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return v1ReceivingAddressControlCapabilitiesRetrieveCall(_callback);

    }

    /**
     *
     *
     * @return ExternalAddressControlCapabilities
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ExternalAddressControlCapabilities v1ReceivingAddressControlCapabilitiesRetrieve() throws ApiException {
        ApiResponse<ExternalAddressControlCapabilities> localVarResp = v1ReceivingAddressControlCapabilitiesRetrieveWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     *
     *
     * @return ApiResponse&lt;ExternalAddressControlCapabilities&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ExternalAddressControlCapabilities> v1ReceivingAddressControlCapabilitiesRetrieveWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = v1ReceivingAddressControlCapabilitiesRetrieveValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ExternalAddressControlCapabilities>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressControlCapabilitiesRetrieveAsync(final ApiCallback<ExternalAddressControlCapabilities> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ReceivingAddressControlCapabilitiesRetrieveValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ExternalAddressControlCapabilities>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ReceivingAddressControlChallengesCreate
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param externalAddressControlChallengeCreate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressControlChallengesCreateCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = externalAddressControlChallengeCreate;

        // create path and map variables
        String localVarPath = "/v1/receiving-address-control-challenges";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ReceivingAddressControlChallengesCreateValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling v1ReceivingAddressControlChallengesCreate(Async)");
        }

        // verify the required parameter 'externalAddressControlChallengeCreate' is set
        if (externalAddressControlChallengeCreate == null) {
            throw new ApiException("Missing the required parameter 'externalAddressControlChallengeCreate' when calling v1ReceivingAddressControlChallengesCreate(Async)");
        }

        return v1ReceivingAddressControlChallengesCreateCall(idempotencyKey, externalAddressControlChallengeCreate, _callback);

    }

    /**
     *
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param externalAddressControlChallengeCreate  (required)
     * @return ExternalAddressControlChallenge
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ExternalAddressControlChallenge v1ReceivingAddressControlChallengesCreate(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate) throws ApiException {
        ApiResponse<ExternalAddressControlChallenge> localVarResp = v1ReceivingAddressControlChallengesCreateWithHttpInfo(idempotencyKey, externalAddressControlChallengeCreate);
        return localVarResp.getData();
    }

    /**
     *
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param externalAddressControlChallengeCreate  (required)
     * @return ApiResponse&lt;ExternalAddressControlChallenge&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ExternalAddressControlChallenge> v1ReceivingAddressControlChallengesCreateWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate) throws ApiException {
        okhttp3.Call localVarCall = v1ReceivingAddressControlChallengesCreateValidateBeforeCall(idempotencyKey, externalAddressControlChallengeCreate, null);
        Type localVarReturnType = new TypeToken<ExternalAddressControlChallenge>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param externalAddressControlChallengeCreate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressControlChallengesCreateAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate, final ApiCallback<ExternalAddressControlChallenge> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ReceivingAddressControlChallengesCreateValidateBeforeCall(idempotencyKey, externalAddressControlChallengeCreate, _callback);
        Type localVarReturnType = new TypeToken<ExternalAddressControlChallenge>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ReceivingAddressesActivateCreate
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressesActivateCreateCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses/{readiness_id}/activate"
            .replace("{" + "readiness_id" + "}", localVarApiClient.escapeString(readinessId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ReceivingAddressesActivateCreateValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling v1ReceivingAddressesActivateCreate(Async)");
        }

        // verify the required parameter 'readinessId' is set
        if (readinessId == null) {
            throw new ApiException("Missing the required parameter 'readinessId' when calling v1ReceivingAddressesActivateCreate(Async)");
        }

        return v1ReceivingAddressesActivateCreateCall(idempotencyKey, readinessId, _callback);

    }

    /**
     *
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @return ExternalReceivingAddress
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ExternalReceivingAddress v1ReceivingAddressesActivateCreate(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId) throws ApiException {
        ApiResponse<ExternalReceivingAddress> localVarResp = v1ReceivingAddressesActivateCreateWithHttpInfo(idempotencyKey, readinessId);
        return localVarResp.getData();
    }

    /**
     *
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @return ApiResponse&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ExternalReceivingAddress> v1ReceivingAddressesActivateCreateWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId) throws ApiException {
        okhttp3.Call localVarCall = v1ReceivingAddressesActivateCreateValidateBeforeCall(idempotencyKey, readinessId, null);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressesActivateCreateAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback<ExternalReceivingAddress> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ReceivingAddressesActivateCreateValidateBeforeCall(idempotencyKey, readinessId, _callback);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ReceivingAddressesCreate
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param externalReceivingAddressCreate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressesCreateCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalReceivingAddressCreate externalReceivingAddressCreate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = externalReceivingAddressCreate;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ReceivingAddressesCreateValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalReceivingAddressCreate externalReceivingAddressCreate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling v1ReceivingAddressesCreate(Async)");
        }

        // verify the required parameter 'externalReceivingAddressCreate' is set
        if (externalReceivingAddressCreate == null) {
            throw new ApiException("Missing the required parameter 'externalReceivingAddressCreate' when calling v1ReceivingAddressesCreate(Async)");
        }

        return v1ReceivingAddressesCreateCall(idempotencyKey, externalReceivingAddressCreate, _callback);

    }

    /**
     *
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param externalReceivingAddressCreate  (required)
     * @return ExternalReceivingAddress
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ExternalReceivingAddress v1ReceivingAddressesCreate(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalReceivingAddressCreate externalReceivingAddressCreate) throws ApiException {
        ApiResponse<ExternalReceivingAddress> localVarResp = v1ReceivingAddressesCreateWithHttpInfo(idempotencyKey, externalReceivingAddressCreate);
        return localVarResp.getData();
    }

    /**
     *
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param externalReceivingAddressCreate  (required)
     * @return ApiResponse&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ExternalReceivingAddress> v1ReceivingAddressesCreateWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalReceivingAddressCreate externalReceivingAddressCreate) throws ApiException {
        okhttp3.Call localVarCall = v1ReceivingAddressesCreateValidateBeforeCall(idempotencyKey, externalReceivingAddressCreate, null);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param externalReceivingAddressCreate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressesCreateAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull ExternalReceivingAddressCreate externalReceivingAddressCreate, final ApiCallback<ExternalReceivingAddress> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ReceivingAddressesCreateValidateBeforeCall(idempotencyKey, externalReceivingAddressCreate, _callback);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ReceivingAddressesList
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressesListCall(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ReceivingAddressesListValidateBeforeCall(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize, final ApiCallback _callback) throws ApiException {
        return v1ReceivingAddressesListCall(cursor, pageSize, _callback);

    }

    /**
     *
     *
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @return List&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public List<ExternalReceivingAddress> v1ReceivingAddressesList(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize) throws ApiException {
        ApiResponse<List<ExternalReceivingAddress>> localVarResp = v1ReceivingAddressesListWithHttpInfo(cursor, pageSize);
        return localVarResp.getData();
    }

    /**
     *
     *
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @return ApiResponse&lt;List&lt;ExternalReceivingAddress&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<ExternalReceivingAddress>> v1ReceivingAddressesListWithHttpInfo(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize) throws ApiException {
        okhttp3.Call localVarCall = v1ReceivingAddressesListValidateBeforeCall(cursor, pageSize, null);
        Type localVarReturnType = new TypeToken<List<ExternalReceivingAddress>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressesListAsync(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize, final ApiCallback<List<ExternalReceivingAddress>> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ReceivingAddressesListValidateBeforeCall(cursor, pageSize, _callback);
        Type localVarReturnType = new TypeToken<List<ExternalReceivingAddress>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ReceivingAddressesReadinessRefreshesCreate
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressesReadinessRefreshesCreateCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses/{readiness_id}/readiness-refreshes"
            .replace("{" + "readiness_id" + "}", localVarApiClient.escapeString(readinessId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ReceivingAddressesReadinessRefreshesCreateValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling v1ReceivingAddressesReadinessRefreshesCreate(Async)");
        }

        // verify the required parameter 'readinessId' is set
        if (readinessId == null) {
            throw new ApiException("Missing the required parameter 'readinessId' when calling v1ReceivingAddressesReadinessRefreshesCreate(Async)");
        }

        return v1ReceivingAddressesReadinessRefreshesCreateCall(idempotencyKey, readinessId, _callback);

    }

    /**
     *
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @return ExternalReceivingAddress
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ExternalReceivingAddress v1ReceivingAddressesReadinessRefreshesCreate(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId) throws ApiException {
        ApiResponse<ExternalReceivingAddress> localVarResp = v1ReceivingAddressesReadinessRefreshesCreateWithHttpInfo(idempotencyKey, readinessId);
        return localVarResp.getData();
    }

    /**
     *
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @return ApiResponse&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ExternalReceivingAddress> v1ReceivingAddressesReadinessRefreshesCreateWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId) throws ApiException {
        okhttp3.Call localVarCall = v1ReceivingAddressesReadinessRefreshesCreateValidateBeforeCall(idempotencyKey, readinessId, null);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressesReadinessRefreshesCreateAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, final ApiCallback<ExternalReceivingAddress> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ReceivingAddressesReadinessRefreshesCreateValidateBeforeCall(idempotencyKey, readinessId, _callback);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ReceivingAddressesRotationsCreate
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @param externalReceivingAddressRotation  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressesRotationsCreateCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, @javax.annotation.Nonnull ExternalReceivingAddressRotation externalReceivingAddressRotation, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = externalReceivingAddressRotation;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses/{readiness_id}/rotations"
            .replace("{" + "readiness_id" + "}", localVarApiClient.escapeString(readinessId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ReceivingAddressesRotationsCreateValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, @javax.annotation.Nonnull ExternalReceivingAddressRotation externalReceivingAddressRotation, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling v1ReceivingAddressesRotationsCreate(Async)");
        }

        // verify the required parameter 'readinessId' is set
        if (readinessId == null) {
            throw new ApiException("Missing the required parameter 'readinessId' when calling v1ReceivingAddressesRotationsCreate(Async)");
        }

        // verify the required parameter 'externalReceivingAddressRotation' is set
        if (externalReceivingAddressRotation == null) {
            throw new ApiException("Missing the required parameter 'externalReceivingAddressRotation' when calling v1ReceivingAddressesRotationsCreate(Async)");
        }

        return v1ReceivingAddressesRotationsCreateCall(idempotencyKey, readinessId, externalReceivingAddressRotation, _callback);

    }

    /**
     *
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @param externalReceivingAddressRotation  (required)
     * @return ExternalReceivingAddress
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ExternalReceivingAddress v1ReceivingAddressesRotationsCreate(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, @javax.annotation.Nonnull ExternalReceivingAddressRotation externalReceivingAddressRotation) throws ApiException {
        ApiResponse<ExternalReceivingAddress> localVarResp = v1ReceivingAddressesRotationsCreateWithHttpInfo(idempotencyKey, readinessId, externalReceivingAddressRotation);
        return localVarResp.getData();
    }

    /**
     *
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @param externalReceivingAddressRotation  (required)
     * @return ApiResponse&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ExternalReceivingAddress> v1ReceivingAddressesRotationsCreateWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, @javax.annotation.Nonnull ExternalReceivingAddressRotation externalReceivingAddressRotation) throws ApiException {
        okhttp3.Call localVarCall = v1ReceivingAddressesRotationsCreateValidateBeforeCall(idempotencyKey, readinessId, externalReceivingAddressRotation, null);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param idempotencyKey Unique mutation key; replaying different content returns HTTP 409. (required)
     * @param readinessId  (required)
     * @param externalReceivingAddressRotation  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ReceivingAddressesRotationsCreateAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull UUID readinessId, @javax.annotation.Nonnull ExternalReceivingAddressRotation externalReceivingAddressRotation, final ApiCallback<ExternalReceivingAddress> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ReceivingAddressesRotationsCreateValidateBeforeCall(idempotencyKey, readinessId, externalReceivingAddressRotation, _callback);
        Type localVarReturnType = new TypeToken<ExternalReceivingAddress>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
