/*
 * x402api Public API
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.x402api.client.api;

import com.x402api.client.core.ApiCallback;
import com.x402api.client.core.ApiClient;
import com.x402api.client.core.ApiException;
import com.x402api.client.core.ApiResponse;
import com.x402api.client.core.Configuration;
import com.x402api.client.core.Pair;
import com.x402api.client.core.ProgressRequestBody;
import com.x402api.client.core.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.x402api.client.model.ApiErrorEnvelope;
import com.x402api.client.model.ExternalAddressControlCapabilities;
import com.x402api.client.model.ExternalReceivingAddress;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ReceivingAddressesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ReceivingAddressesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ReceivingAddressesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for receivingAddressesGetControlCapabilities
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for get receiving-address control capabilities. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesGetControlCapabilitiesCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/receiving-address-control-capabilities";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call receivingAddressesGetControlCapabilitiesValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return receivingAddressesGetControlCapabilitiesCall(_callback);

    }

    /**
     * Get receiving-address control capabilities
     * Return the supported proof and control capabilities for external receiving addresses. Requires a tenant API key with the &#x60;wallets:read&#x60; scope.
     * @return ExternalAddressControlCapabilities
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for get receiving-address control capabilities. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ExternalAddressControlCapabilities receivingAddressesGetControlCapabilities() throws ApiException {
        ApiResponse<ExternalAddressControlCapabilities> localVarResp = receivingAddressesGetControlCapabilitiesWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get receiving-address control capabilities
     * Return the supported proof and control capabilities for external receiving addresses. Requires a tenant API key with the &#x60;wallets:read&#x60; scope.
     * @return ApiResponse&lt;ExternalAddressControlCapabilities&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for get receiving-address control capabilities. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<ExternalAddressControlCapabilities> receivingAddressesGetControlCapabilitiesWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = receivingAddressesGetControlCapabilitiesValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ExternalAddressControlCapabilities>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get receiving-address control capabilities (asynchronously)
     * Return the supported proof and control capabilities for external receiving addresses. Requires a tenant API key with the &#x60;wallets:read&#x60; scope.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for get receiving-address control capabilities. </td><td>  * X-Request-ID -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesGetControlCapabilitiesAsync(final ApiCallback<ExternalAddressControlCapabilities> _callback) throws ApiException {

        okhttp3.Call localVarCall = receivingAddressesGetControlCapabilitiesValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ExternalAddressControlCapabilities>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for receivingAddressesList
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for list receiving addresses. </td><td>  * X-Request-ID -  <br>  * Link -  <br>  * X-X402API-Next-Cursor -  <br>  * X-X402API-Result-Truncated -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesListCall(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/receiving-addresses";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "tenantApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call receivingAddressesListValidateBeforeCall(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize, final ApiCallback _callback) throws ApiException {
        return receivingAddressesListCall(cursor, pageSize, _callback);

    }

    /**
     * List receiving addresses
     * List tenant receiving-address registrations using opaque cursor pagination. Requires a tenant API key with the &#x60;wallets:read&#x60; scope.
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @return List&lt;ExternalReceivingAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for list receiving addresses. </td><td>  * X-Request-ID -  <br>  * Link -  <br>  * X-X402API-Next-Cursor -  <br>  * X-X402API-Result-Truncated -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public List<ExternalReceivingAddress> receivingAddressesList(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize) throws ApiException {
        ApiResponse<List<ExternalReceivingAddress>> localVarResp = receivingAddressesListWithHttpInfo(cursor, pageSize);
        return localVarResp.getData();
    }

    /**
     * List receiving addresses
     * List tenant receiving-address registrations using opaque cursor pagination. Requires a tenant API key with the &#x60;wallets:read&#x60; scope.
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @return ApiResponse&lt;List&lt;ExternalReceivingAddress&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for list receiving addresses. </td><td>  * X-Request-ID -  <br>  * Link -  <br>  * X-X402API-Next-Cursor -  <br>  * X-X402API-Result-Truncated -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<List<ExternalReceivingAddress>> receivingAddressesListWithHttpInfo(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize) throws ApiException {
        okhttp3.Call localVarCall = receivingAddressesListValidateBeforeCall(cursor, pageSize, null);
        Type localVarReturnType = new TypeToken<List<ExternalReceivingAddress>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List receiving addresses (asynchronously)
     * List tenant receiving-address registrations using opaque cursor pagination. Requires a tenant API key with the &#x60;wallets:read&#x60; scope.
     * @param cursor Opaque pagination cursor from X-X402API-Next-Cursor or rel&#x3D;next Link. (optional)
     * @param pageSize Number of results in the bounded array page (default and maximum 100). (optional, default to 100)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response for list receiving addresses. </td><td>  * X-Request-ID -  <br>  * Link -  <br>  * X-X402API-Next-Cursor -  <br>  * X-X402API-Result-Truncated -  <br>  </td></tr>
        <tr><td> 0 </td><td> The request failed with a stable machine-readable error. </td><td>  * X-Request-ID -  <br>  * Retry-After -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call receivingAddressesListAsync(@javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer pageSize, final ApiCallback<List<ExternalReceivingAddress>> _callback) throws ApiException {

        okhttp3.Call localVarCall = receivingAddressesListValidateBeforeCall(cursor, pageSize, _callback);
        Type localVarReturnType = new TypeToken<List<ExternalReceivingAddress>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
